#!/usr/bin/env python3
"""DJ Catnip voice pack (Gabby's Dollhouse): rewrites of the stock Dreame prompts.

DJ Catnip is a small, hyper-enthusiastic music-loving cat DJ. The register is the
opposite of C-3PO: upbeat, hip, bouncy, kid-friendly, forever about to drop a
beat. Cat puns and music/DJ slang carry the personality; exclamation marks and
CAPS carry the delivery (eleven_v3 reads energy off the punctuation).

Same rules as every pack:
* Keep the functional payload — which part failed, what the human must do.
* Keep it short; these play while the robot works.
* Room names, numbers and percentages stay verbatim.
* Not everything is maximum hype, or the hype stops landing. Errors get a quick
  "uh-oh"; routine status gets the swagger; completion gets the celebration.

This is a DRAFT for review: the high-traffic prompts and one of every category
are written, plus the room and battery templates in full. Lines still marked
MISSING by merge_rewrites are the remaining fill-in work, held until the voice
and direction are approved.
"""

META = {
    "name": "djcatnip",
    "title": "DJ Catnip",
    "language_code": "CATNIP",
    "voice_tag": "VOICE",         # key in this pack's voices.json
    "profile": "p0",           # a cartoon cat, not a droid — clean, no processing
    "description": "DJ Catnip from Gabby's Dollhouse: hyper, hip, music-loving cat DJ.",
}

SKIP = {
    0: "startup chime",
    200: "shutdown chime",
    274: "'Ding!' — a notification tone, not speech",
    488: "not speech; whisper hallucinated a document header",
}

REWRITES = {
    # --- cleaning start / status (the ones you hear most) ----------------
    7: "[excited] DJ Catnip in the house! Let's clean this floor — drop the beat!",
    8: "Spot cleaning! One little groove spot comin' up!",
    9: "Scheduled clean, right on the beat! Let's go!",
    10: "[excited] And we're back! Pickin' the track up where we left off!",
    11: "Hold up — pausin' the track!",
    12: "[excited] Booyah! Floor's spotless and the beat goes on! Purr-fect!",
    143: "[excited] And that's a wrap! Clean floors all day! Yeah!",
    144: "[excited] Moppin' done and the whole place is shinin'! Meow-velous!",
    61: "Moppin' time! Watch the wet floor, cool cat!",
    190: "You got it — cleanin' now! Let's gooo!",
    193: "Vacuumin'! Turn it up!",
    192: "Moppin'! Smooth and groovy.",
    201: "Keep it rollin' — back to work!",
    221: "You got it!",

    # --- battery / dock --------------------------------------------------
    13: "Rollin' back to the DJ booth to recharge!",
    14: "[anxious] Yo, battery's low! Headin' back to juice up — I'll finish the set after!",
    20: "[anxious] Uh-oh, battery's runnin' low, cool cat!",
    47: "Chargin' up! Rechargin' these beats.",
    18: "[excited] Back at the booth! Let's gooo!",

    # --- errors / faults -------------------------------------------------
    40: "[anxious] Aw snap, I'm stuck! Somebody clear the way so I can groove!",
    34: "[anxious] Hey, my dust bin's missing! Pop it back in so we can jam!",
    35: "[anxious] My main brush is actin' up! Give it a check and a clean, would ya?",
    42: "My filter needs some love — give it a clean!",
    44: "Uh-oh, somethin's off the beat! Check the manual or hit up support.",
    41: "[anxious] My wheels are off the ground! Set me down and hit play again!",

    # --- consumables -----------------------------------------------------
    102: "[anxious] Dust bag's full or the duct's clogged! Swap the bag or clear it out!",
    93: "My water tank's runnin' dry — top me up!",
    111: "[anxious] My mop pads fell off! Pop 'em back on before we drop the beat!",

    # --- network ---------------------------------------------------------
    5: "[excited] Network's connected! We are LIVE!",
    2: "[anxious] Aw, can't reach the Wi-Fi! Check the password and try again.",

    # --- voice assistant -------------------------------------------------
    45: "I'm right here, cool cat!",
    208: "[excited] Found ya! Comin' over to clean!",
    247: "Say what now? Didn't quite catch that beat!",
}

# Room prompts (492-507): only the room name varies, and it stays verbatim.
ROOMS = {
    492: "living room", 493: "bedroom", 494: "master room", 495: "guest room",
    496: "study", 497: "kitchen", 498: "dining room", 499: "bathroom",
    500: "balcony", 501: "hallway", 502: "utility room", 503: "closet",
    504: "drawing room", 505: "office", 506: "gym", 507: "recreation area",
}
for _id, _room in ROOMS.items():
    REWRITES[_id] = f"Alright, cleanin' the {_room} — let's gooo! Keep the door open!"

# Battery announcements (526-626, counting 100 down to 0). Plain by design — the
# number is the point — with a little swagger only at the extremes.
for _pct in range(0, 101):
    _id = 626 - _pct
    if _pct == 0:
        REWRITES[_id] = "[anxious] Battery at zero, cool cat — I'm tapped out!"
    elif _pct == 100:
        REWRITES[_id] = "[excited] Battery at one hundred percent — fully charged and ready to spin!"
    elif _pct <= 10:
        REWRITES[_id] = f"[anxious] Battery at {_pct} percent — gettin' low!"
    else:
        REWRITES[_id] = f"Battery at {_pct} percent."

# --- remaining lines (full set) --------------------------------------------
REWRITES.update({
    1: "[anxious] Yo, still waitin' on the network setup — let's get connected!",
    3: "[anxious] Aw, can't reach the server! Check your network and try again.",
    4: "Aight, exited network setup mode. We good.",
    6: "[anxious] Network hookup flopped — give it another shot in a bit.",
    17: "[anxious] Yo, put me back on the base station — I can't do it solo!",
    19: "[anxious] Take me OFF the base before you power me down!",
    21: "[anxious] Battery's toast — powerin' down! Later!",
    25: "[anxious] Too low for the scheduled clean — bummer!",
    26: "[anxious] Factory reset — wipin' it all! Whoa.",
    27: "[anxious] Updatin' — 'bout five minutes! Don't power me down, don't start a clean!",
    28: "[excited] Update done — we good!",
    29: "[anxious] Update flopped — try again later.",
    30: "Findin' my spot — hang on.",
    31: "[anxious] Lost the map — startin' a fresh clean!",
    36: "[anxious] Side brush trippin'! Check it and clean it.",
    37: "[anxious] Right wheel's actin' up! Check it and clean it.",
    38: "[anxious] Left wheel's actin' up! Check it and clean it.",
    39: "[anxious] My wheels ain't touchin' down! Wipe the cliff sensors, set me down, hit play!",
    43: "[anxious] Bumper's buggin' — give it a tap and see if it bounces back!",
    46: "Robot and phone linked up! Head back to the app for the result.",
    48: "[anxious] Battery low — rollin' back to the dock.",
    50: "[anxious] Chargin' hiccup! Wipe them charge contacts!",
    52: "[anxious] I'm tilted! Set me on level ground and restart!",
    54: "[excited] Locked in! Resumin' the clean!",
    55: "[excited] Locked in! Rollin' back to the dock!",
    56: "Selected room cleanin'! Let's pick our spots.",
    57: "Zoned cleanin'! Stayin' in the groove zone.",
    58: "Keepin' the cleanin' goin'! Let's ride.",
    62: "Remote control mode — you drive, I groove!",
    64: "[anxious] Lost my spot — rollin' back to the dock.",
    65: "Back to the dock — almost there!",
    66: "[anxious] Filter's worn out — swap it soon!",
    67: "[anxious] Side brush is worn out — swap it soon!",
    68: "[anxious] Main brush is worn out — swap it soon!",
    71: "[anxious] Laser sensor's trippin'! Check it and clean it.",
    72: "[anxious] Check if the laser cover's jammed, cool cat!",
    73: "[anxious] Edge sensor's actin' up! Check it and clean it.",
    75: "[anxious] Filter's damp or clogged — neither's a vibe.",
    77: "[anxious] Start me somewhere that ain't carpet, please!",
    82: "Mappin' the place — layin' down the blueprint!",
    83: "Keepin' the map goin'!",
    84: "[excited] Map's done — masterpiece!",
    85: "[excited] Locked in! Keepin' the map rollin'!",
    86: "[anxious] Lost my spot — startin' the map over!",
    87: "[anxious] Battery low — rollin' back to the dock!",
    91: "[anxious] Fresh tank's missin'! Pop it in!",
    97: "[anxious] Put the dust bag in — can't jam without it!",
    105: "Cleanin'! Let's go!",
    106: "Washin' my mop pads — freshen up!",
    107: "Dryin' the mop pads — hang tight!",
    108: "[anxious] Washboard water level's off! Clean it soon!",
    109: "[anxious] Waste tank's trippin'! Make sure it's in AND empty!",
    110: "Auto-empty — stand back, it's loud!",
    112: "[anxious] Set me in the base station first, cool cat!",
    113: "[excited] Task done! Empty the waste tank when ya can!",
    114: "Mop pads on! We good.",
    115: "Mop pads off! Nice and easy.",
    116: "Child lock on — buttons locked down!",
    117: "Child lock off — buttons unlocked!",
    118: "[anxious] Buttons locked! Hold the dock button to unlock!",
    126: "Cleanin'! Let's gooo!",
    127: "Spot cleanin' — quick lil' number.",
    128: "Spot moppin' — one wet spot comin' up!",
    129: "Scheduled cleanin', right on time!",
    130: "Scheduled moppin', punctual as a metronome!",
    133: "Cleanin' the room you picked — let's go!",
    134: "Moppin' the room you picked — mind the wet floor!",
    135: "Zoned cleanin' — stayin' in the lines!",
    136: "Zoned moppin' — strictly in the zone!",
    137: "Back on it — resumin' the clean!",
    138: "Back on the map — resumin'!",
    139: "Rollin' back!",
    140: "[anxious] New spot detected! Rollin' back to base!",
    142: "[anxious] Mop pad's worn out — swap it soon!",
    145: "[excited] Locked in! Resumin' the clean!",
    146: "[excited] Locked in! Back on the map!",
    148: "Rollin' back to base for a self-clean — brb!",
    149: "[anxious] Can't reach that spot! Clear the path for me!",
    150: "[anxious] Can't reach that spot! Ditch the no-go zones in my way!",
    151: "[anxious] Path's blocked! Clear the stuff around me!",
    152: "[anxious] Path's blocked! Delete a no-go zone or scoot me outta here!",
    153: "[anxious] I'm in a no-go zone! Move me outta here!",
    156: "[anxious] Mop pad ain't installed!",
    162: "Camera's on — I see ya!",
    163: "Camera monitorin' — watchin' the floor!",
    164: "That's the end of the set! Peace.",
    166: "[anxious] Somethin's tangled in my mop pad — clean it out!",
    169: "Mop pad's dry — crispy clean!",
    171: "AI recognition on — I'm gettin' smart!",
    172: "AI recognition off — back to freestyle!",
    173: "[anxious] Swap the Silver Ion sterilizer — it's spent!",
    177: "Rollin' out the booth!",
    179: "[anxious] Mop pad's clean but the clean tank's low! Fill it and empty the used one!",
    181: "[anxious] Low on water! Fill the clean tank!",
    186: "[anxious] Check the fresh tank, would ya?",
    187: "'Bout five to ten minutes — hang tight!",
    188: "Auto-dockin' — homeward bound!",
    191: "Vacuumin' AND moppin' — double feature, let's go!",
    194: "Been cleanin', thanks for checkin'!",
    195: "Aight, cleanin' the room — keep the door open!",
    196: "Aight, vacuumin' the floor — keep the door open!",
    197: "Aight, moppin' the floor — keep the door open!",
    198: "Aight, vacuumin' AND moppin' — keep the door open!",
    199: "[anxious] Don't know this room! Check the name in the app!",
    202: "That's a wrap — rollin' back to charge!",
    203: "Headin' back to charge — catch ya soon!",
    204: "Aight, mappin' now — keep ALL the doors open!",
    205: "Rollin' out the booth — let's go!",
    206: "Aight, I'll try to find ya! Stay put!",
    207: "[anxious] Can't find ya! Stand where I can see ya!",
    209: "Aight, rollin' back to wash the mop pad!",
    210: "Washin' the mop pad — squeaky clean!",
    211: "[anxious] Can't self-empty unless I'm in the dock, cool cat!",
    212: "Aight, auto-emptyin' — stand back!",
    213: "[anxious] Can't dry unless I'm in the dock!",
    214: "Dryin' — hang tight!",
    215: "Aight, dryin' now!",
    216: "[anxious] Pop the mop pad on first!",
    217: "Max suction — full power, let's go!",
    218: "Min suction — barely a whisper.",
    219: "Max humidity — steamy in here!",
    220: "Min humidity — nice and dry.",
    222: "Suction mode: quiet — low-key vibes.",
    223: "Suction mode: standard — steady groove.",
    224: "Suction mode: strong — turn it up!",
    225: "Suction mode: turbo — hold onto somethin'!",
    226: "Mop pad's slightly dry — just right.",
    227: "Mop pad's moist — smooth.",
    228: "Mop pad's wet — soaked and ready.",
    229: "Today is...",
    230: "Today's February twenty-first, twenty twenty-two.",
    231: "It's Monday — week's on!",
    232: "It's Tuesday.",
    233: "It's Wednesday — halfway, baby!",
    234: "It's Thursday.",
    235: "It's Friday — almost the weekend!",
    236: "It's Saturday — chill day!",
    237: "It's Sunday — take it easy!",
    238: "Aight, task's paused — take five!",
    244: "Detergent bottle's in — classy!",
    245: "[anxious] Hit the map limit! Delete one and try again!",
    246: "I'm right here!",
    248: "[anxious] Mop pad ain't installed! Pop it on and try again!",
    249: "[anxious] I'm workin'! End the current task and try again!",
    250: "[anxious] I'm in mop mode! Switch to vacuum, or vacuum-and-mop first!",
    251: "[anxious] I'm in vacuum mode! Switch to mop, or vacuum-and-mop first!",
    252: "Done — outta custom mode! Freedom!",
    253: "Max volume — can't get louder, cool cat!",
    254: "Min volume — barely hear myself.",
    255: "[anxious] That needs smart obstacle dodge switched on, cool cat!",
    257: "Camera monitorin' off — privacy's back.",
    258: "Locked in — cruisin'!",
    259: "Locked in — headin' to the spot!",
    260: "Locked in — cruisin' again!",
    261: "Locked in — back to the spot!",
    262: "[anxious] Couldn't find my spot — total blank.",
    266: "[anxious] Swap the detergent — it's tapped out!",
    267: "[anxious] Clean my sensors — I can barely see!",
    269: "[anxious] Try again once I'm done with this one!",
    275: "Didn't catch that one — open the app for more commands!",
    276: "[anxious] I ain't doin' that task, cool cat.",
    277: "Aight, comin' over to clean up there!",
    278: "Dryin's done — all crisp!",
    279: "[anxious] I'm vacuumin'! End the task and try again!",
    280: "Custom cleanin' — made to order!",
    283: "[anxious] I ain't in the base station — try again in a bit.",
    284: "Aight, I'll wrap this and come clean!",
    285: "Hang tight a sec while I find ya!",
    286: "[anxious] Make a map first and try again!",
    287: "Aight, switched to quiet mode — low-key!",
    288: "Aight, switched to standard mode.",
    289: "Aight, switched to strong mode — turn it up!",
    290: "Aight, switched to turbo mode — whoa!",
    291: "Aight, switched to slightly dry mode.",
    292: "Aight, switched to wet mode — mind the splash!",
    293: "Callin's on — ring me anytime!",
    294: "Callin's off — quiet time.",
    296: "[anxious] Used water tank's trippin'! Check if it's full!",
    297: "Detergent bottle's in! If it's brand new, reset it in the app.",
    298: "[anxious] Base station self-clean! Scrub inside with a brush or cloth — sewage drains in three minutes!",
    299: "Detergent bottle and auto-add module installed — fancy!",
    300: "[anxious] Don't support that accessory, cool cat.",
    301: "Chargin' up! Rechargin' the vibes.",
    302: "I'm workin' — busy droppin' beats!",
    303: "[anxious] Kinda dazed over here, cool cat.",
    304: "Network's connected! We rollin'.",
    305: "Cleanin' the washboard base! Scrub inside with a brush or cloth — sewage drains in three minutes.",
    306: "[anxious] Didn't catch that — set up the network and try again.",
    307: "Chargin' — let me juice up.",
    308: "Didn't catch that — wake me and try again!",
    309: "[excited] Found ya! Rollin' over!",
    310: "Aight, rollin' outta this area right now!",
    312: "No usage info on this accessory — swap it whenever ya need.",
    313: "[anxious] Signal's weak out here! Move me somewhere with better vibes!",
    314: "That ain't supported — but you can tell me to spin around!",
    315: "[anxious] Mop pad ain't in the dock! Pop it in and try again!",
    317: "[anxious] Can't do that mid custom clean — edit it in the app!",
    318: "[excited] Task done! Booyah!",
    321: "Intensive stain moppin' — scrubbin' with soul!",
    322: "Didn't catch that — open the app for all my commands!",
    323: "Didn't catch that — ask me what I can do and I'll break it down!",
    324: "Washin' my mop pad — wake me when it's done!",
    328: "[anxious] Only give me that one while I'm cleanin', cool cat!",
    329: "Self-testin'! Don't move me off the base station!",
    330: "[anxious] Try again when the self-test's done!",
    331: "[excited] No faults — I'm in top shape, baby!",
    332: "[anxious] Found one fault — peep the app for details!",
    338: "[excited] Video call's on — we live!",
    339: "Call declined — cold, cool cat.",
    340: "No answer — nobody's pickin' up.",
    344: "Vacuum first, then mop — in that order, cool cat!",
    346: "This is the bin. Catch ya next time!",
    356: "[anxious] Still faulty — scheduled task's canceled. Bummer.",
    360: "Drainin' my water tank — 'scuse the noise!",
    361: "Water tank's drained — all dry!",
    363: "Vacuumin's done — moppin' time! No breaks!",
    364: "Settin' the video code — keep it secret!",
    365: "Live video's off — privacy's back.",
    366: "[excited] Stain spotted! Movin' in to clean it!",
    367: "Aight — stain cleanin'! Stand back!",
    368: "[excited] Ooh, a stain! I'll hit it after I wash up!",
    369: "Aight, spot cleanin'!",
    371: "[anxious] Take the washboard out, would ya?",
    372: "Clean water's flowin' — mind the splash!",
    373: "Water flow's done — wait ten seconds for the dirt to soak, then clean the base station.",
    374: "[anxious] Clean the bottom of the base station in twenty seconds — then the sewage pumps out!",
    375: "Push the dirt to the pump port — pumpin' for thirty seconds!",
    376: "Pumpin's done — clean the washboard separate and pop it back!",
    377: "[anxious] Can't set up the network, cool cat! Hit up support.",
    378: "[anxious] Wrong password — network shut me down. Set it up again!",
    379: "[anxious] No Wi-Fi found! Hop on the 2.4 gig band and scoot me near the router.",
    380: "[anxious] Couldn't grab an IP address — check them router settings!",
    381: "[anxious] Can't reach the server! Give support a shout.",
    382: "[anxious] Network connect flopped — make sure your net's up and runnin'.",
    383: "[anxious] Network setup's a no-go, cool cat. Hit up support.",
    384: "[anxious] No water in the auto-supply clean tank! Bummer!",
    385: "Hookin' up to the network now — stand by!",
    388: "[anxious] Hidden spot! Move me somewhere open and try again!",
    392: "[anxious] Can't tweak settings in Clean Genius mode, cool cat!",
    396: "Emptyin' the water supply module — 'bout three minutes!",
    397: "Upper and lower drainage done — crisp!",
    426: "[anxious] Whoa, I slipped and I'm stuck! I'll keep wigglin' free!",
    433: "Extra cleanin' — goin' the extra mile!",
    434: "Extra cleanin's done — back to the main track!",
    435: "Rollin' outta this area!",
    440: "[anxious] Wheels are hangin'! Move me to open ground and restart!",
    441: "[anxious] Main brush is tangled! Pull it, clean it, pop it back!",
    442: "[anxious] Side brush is tangled! Pull it, clean it, pop it back!",
    444: "[anxious] Set me down somewhere open before we start — I need room!",
    445: "[anxious] My mop fell off! Find it near me and pop it back on!",
    447: "[anxious] Dock's got no power! Check it and put me back to charge!",
    451: "[anxious] Can't start in a hidden spot! Move me elsewhere and restart!",
    460: "[anxious] Used water tank deodorizer's worn out — swap it soon!",
    489: "[anxious] I'm in Clean Genius mode! Tell me to end it and try again!",
    490: "Aight — custom mode, moppin'!",
    491: "Aight — custom mode, vacuumin'!",
    508: "Aight, cranked the volume UP!",
    509: "Aight, turned the volume down — chill.",
    510: "Aight, that's the set — we done!",
    511: "[anxious] I ain't doin' a task right now, cool cat.",
    512: "[anxious] Map's got no pet furniture yet — add it in the app!",
    513: "Aight, rollin' over to clean 'round the pet furniture!",
    516: "Huntin' for pets — here, kitty kitty!",
    517: "[excited] Found the pets! Rollin' back to charge!",
    518: "[anxious] No pets found — bummer. Rollin' back to charge.",
    636: "[anxious] My mop's grimy! Roll me to the dock for a wash!",
    638: "Back to the auto-empty — stand back!",
})
