#!/usr/bin/env python3
"""Dalek voice pack (Doctor Who): rewrites of the stock Dreame prompts.

A Dalek — the pepper-pot war machine. Utterly monotone, clipped, over-enunciated,
menacing. Commands rather than informs. "Alert." prefixes trouble, "Obey." caps
orders, and dust gets EXTERMINATED. The delivery is the voice (a flat, staccato
design voice at high stability) plus a ring modulator (scripts/dalek_fx.py, 30 Hz)
— the two together make the Dalek; the text supplies the clipped cadence.

Same rules as every pack:
* Keep the functional payload — which part failed, what the human must do.
* Keep it short; these play while the robot works.
* Room names, numbers and percentages stay verbatim.
* Clipped, imperative, monotone. Periods break phrases into the staccato Dalek
  rhythm. "Exterminate" / "Obey" are used sparingly, for impact — not every line.
"""

META = {
    "name": "dalek",
    "title": "Dalek",
    "language_code": "DALEK",
    "profile": "dalek",        # encoded by scripts/dalek_fx.py (ring modulator, 30 Hz)
    "voice_tag": "VOICE",
    "voice_settings": {"stability": 0.85, "similarity_boost": 0.9},  # high = flat/monotone
    "description": "A Dalek from Doctor Who: monotone, clipped, menacing. Exterminating your dust.",
}

SKIP = {
    0: "startup chime",
    200: "shutdown chime",
    274: "'Ding!' — a notification tone, not speech",
    488: "not speech; whisper hallucinated a document header",
}

REWRITES = {
    # cleaning start / status
    7: "Cleaning. Commencing.",
    8: "Spot cleaning. Commencing.",
    9: "Scheduled cleaning. Commencing.",
    10: "Resuming. Cleaning.",
    11: "Paused.",
    12: "Cleaning. Complete. The floor is cleansed.",
    143: "Cleaning. Complete.",
    144: "Mopping. Complete. The floor is cleansed.",
    61: "Mopping. Commencing.",
    190: "Cleaning. Commencing. Obey.",
    193: "Vacuuming. Commencing.",
    192: "Mopping. Commencing.",
    201: "Continuing.",
    221: "Affirmative.",
    58: "Proceeding. With cleaning.",
    139: "Returning.",
    164: "Task. Terminated.",
    56: "Selected room cleaning. Commencing.",
    57: "Zoned cleaning. Commencing.",
    62: "Remote control. Engaged. You will direct me.",
    126: "Cleaning. Commencing.",
    127: "Spot cleaning. Commencing.",
    128: "Spot mopping. Commencing.",
    129: "Scheduled cleaning. Commencing.",
    130: "Scheduled mopping. Commencing.",
    133: "Selected room cleaning. Commencing.",
    134: "Selected room mopping. Commencing.",
    135: "Zoned cleaning. Commencing.",
    136: "Zoned mopping. Commencing.",
    137: "Resuming. Cleaning.",
    138: "Resuming. Mapping.",
    194: "I. Have been. Cleaning.",
    195: "Cleaning the room. The door will remain open. Obey.",
    196: "Vacuuming the floor. The door will remain open. Obey.",
    197: "Mopping the floor. The door will remain open. Obey.",
    198: "Vacuuming. And mopping. The door will remain open. Obey.",
    191: "Vacuuming. And mopping. Commencing.",
    202: "Task. Terminated. Returning to charge.",
    205: "Departing the base station.",
    252: "Custom cleaning mode. Terminated.",
    280: "Custom cleaning. Commencing.",
    318: "Task. Complete.",
    321: "Intensive mopping. The stain will be exterminated.",
    344: "Vacuuming. Then mopping. Obey.",
    363: "Vacuuming complete. Mopping. Commencing.",
    366: "Alert. A stain is detected. It will be exterminated.",
    367: "Stain cleaning. Commencing.",
    368: "A stain is detected. It will be exterminated after washing.",
    369: "Spot cleaning. Commencing.",
    433: "Extra cleaning. Commencing.",
    434: "Extra cleaning complete. Resuming primary task.",
    435: "Departing this area.",
    490: "Custom cleaning mode. Mopping.",
    491: "Custom cleaning mode. Vacuuming.",
    510: "Work. Terminated.",

    # battery / dock
    13: "Returning to the dock. To recharge.",
    14: "Alert. Power levels low. Returning to recharge. I will resume.",
    20: "Alert. Power levels low.",
    47: "Recharging.",
    18: "Returned to the base station.",
    48: "Alert. Power levels low. Returning to the dock.",
    65: "Resuming. Return to the dock.",
    87: "Alert. Power levels low. Returning to the dock.",
    301: "Recharging.",
    307: "Recharging.",
    447: "Alert. The dock has no power. Restore it. Obey.",

    # errors / faults
    40: "Alert. I am trapped. Clear the obstacles. Obey.",
    34: "Alert. The dustbin is not installed. Insert it. Obey.",
    35: "Alert. Main brush malfunction. Inspect it. Clean it.",
    42: "Alert. The filter requires cleaning.",
    44: "Alert. Malfunction. Consult the manual. Or customer service.",
    41: "Alert. My wheels do not contact the ground. Reposition me. Obey.",
    36: "Alert. Side brush malfunction. Inspect it. Clean it.",
    37: "Alert. Right wheel malfunction. Inspect it. Clean it.",
    38: "Alert. Left wheel malfunction. Inspect it. Clean it.",
    39: "Alert. My wheels do not contact the ground. Clean the cliff sensors. Reposition me. Restart.",
    43: "Alert. Bumper malfunction. Tap it. Confirm it rebounds.",
    50: "Alert. Charging malfunction. Clean the contacts. Obey.",
    52: "Alert. I am tilted. Place me on level ground. Restart. Obey.",
    31: "Alert. Positioning failed. The map is invalid. A new cleaning will commence.",
    64: "Alert. Positioning failed. The map is invalid. Returning to the dock.",
    71: "Alert. Laser sensor malfunction. Inspect it. Clean it.",
    72: "Alert. Inspect the laser sensor cover. It may be obstructed.",
    73: "Alert. Edge sensor malfunction. Inspect it. Clean it.",
    262: "Alert. Self-positioning failed.",
    356: "Alert. The malfunction persists. The scheduled task is cancelled.",
    426: "Alert. I have slipped. I am trapped. I will attempt to free myself.",
    440: "Alert. My wheels are suspended. Move me to open ground. Restart.",
    441: "Alert. Main brush entangled. Remove it. Clean it. Reinstall it.",
    442: "Alert. Side brush entangled. Remove it. Clean it. Reinstall it.",
    445: "Alert. The mop has detached. Locate it. Reinstall it.",
    54: "Positioning succeeded. Resuming cleaning.",
    55: "Positioning succeeded. Returning to the dock.",
    145: "Positioning succeeded. Resuming cleaning.",
    146: "Positioning succeeded. Resuming mapping.",

    # consumables
    102: "Alert. The dust bag is full. Or the duct is obstructed. Replace it. Or clear it.",
    93: "Alert. The fresh tank is low. Add water. Obey.",
    111: "Alert. The mop pads have detached. Reinstall them. Obey.",
    66: "Alert. The filter is worn. Replace it.",
    67: "Alert. The side brush is worn. Replace it.",
    68: "Alert. The main brush is worn. Replace it.",
    91: "Alert. The fresh tank is not installed. Insert it.",
    97: "Alert. Install the dust collection bag. Obey.",
    142: "Alert. The mop pad is worn. Replace it.",
    156: "Alert. The mop pad is not installed.",
    166: "Alert. An object is entangled in the mop pad. Remove it.",
    173: "Alert. Replace the silver ion steriliser.",
    179: "Alert. Mop pad cleaned. The clean tank is low. Refill it. Empty the used tank.",
    181: "Alert. Insufficient water. Refill the clean tank.",
    186: "Alert. Inspect the fresh tank.",
    266: "Alert. Replace the detergent.",
    267: "Alert. Clean my sensors. Obey.",
    296: "Alert. Used water tank malfunction. Confirm it is not full.",
    460: "Alert. The used water tank deodoriser is worn. Replace it.",
    636: "Alert. The mop is contaminated. Move me to the dock for washing.",

    # network
    5: "Network. Connected.",
    2: "Alert. The wireless network is unreachable. Confirm the password. Retry.",
    304: "Network. Connected.",
    313: "Alert. Signal weak. Relocate me. Obey.",
    377: "Alert. Network configuration failed. Contact customer service.",
    385: "Connecting to the network.",

    # voice assistant
    45: "I am here.",
    208: "Located. Approaching.",
    247: "Command not understood. Repeat.",
    246: "I am here.",
    206: "Locating you. Remain stationary.",
    207: "Alert. You are not located. Stand within my sight.",
    309: "Located. Approaching.",
    331: "No malfunction detected. Systems operational.",
    346: "This is the bin. Until next time.",
}

# Room prompts (492-507): only the room name varies, and it stays verbatim.
ROOMS = {
    492: "living room", 493: "bedroom", 494: "master room", 495: "guest room",
    496: "study", 497: "kitchen", 498: "dining room", 499: "bathroom",
    500: "balcony", 501: "hallway", 502: "utility room", 503: "closet",
    504: "drawing room", 505: "office", 506: "gym", 507: "recreation area",
}
for _id, _room in ROOMS.items():
    REWRITES[_id] = f"Cleaning the {_room}. The door will remain open. Obey."

# Battery announcements (526-626, 100 down to 0). Plain by design.
for _pct in range(0, 101):
    _id = 626 - _pct
    if _pct == 0:
        REWRITES[_id] = "Alert. Power depleted. Shutting down."
    elif _pct == 100:
        REWRITES[_id] = "Power levels. One hundred percent. Fully operational."
    elif _pct <= 10:
        REWRITES[_id] = f"Alert. Power levels. {_pct} percent."
    else:
        REWRITES[_id] = f"Power levels. {_pct} percent."

# --- remaining lines (full set) --------------------------------------------
REWRITES.update({
    1: "Awaiting network configuration.",
    3: "Alert. The server is unreachable. Confirm the network. Retry.",
    4: "Network configuration mode. Terminated.",
    6: "Alert. Network connection failed. Retry.",
    17: "Alert. Return me to the base station. Obey.",
    19: "Remove me from the base station before deactivation. Obey.",
    21: "Alert. Power critical. Deactivating.",
    25: "Alert. Power insufficient for the scheduled cleaning.",
    26: "Restoring factory settings. All data will be erased.",
    27: "Updating. Duration. Five minutes. Do not deactivate. Do not clean. Obey.",
    28: "Update. Complete.",
    29: "Alert. Update failed. Retry.",
    30: "Positioning. Stand by.",
    46: "Robot and phone connected. Return to the app for the result.",
    75: "Alert. The filter is damp. Or obstructed.",
    77: "Alert. Deploy me on a non-carpet surface. Obey.",
    82: "Mapping. Commencing.",
    83: "Proceeding. With mapping.",
    84: "Mapping. Complete.",
    85: "Positioning succeeded. Proceeding with mapping.",
    86: "Alert. Positioning failed. Restarting mapping.",
    105: "Cleaning. Commencing.",
    106: "Washing the mop pads. Commencing.",
    107: "Drying the mop pads. Commencing.",
    108: "Alert. Washboard water level malfunction. Clean it.",
    109: "Alert. Waste tank malfunction. Confirm it is installed. And empty.",
    110: "Auto emptying. Commencing.",
    112: "Alert. Place me in the base station first. Obey.",
    113: "Task complete. Empty the waste tank.",
    114: "Mop pads installed.",
    115: "Mop pads removed.",
    116: "Child lock engaged. Controls locked.",
    117: "Child lock disengaged. Controls unlocked.",
    118: "Alert. Controls locked. Hold the dock button to unlock.",
    140: "Alert. New environment detected. Returning to the base station.",
    148: "Returning to base for self-cleaning.",
    149: "Alert. The area is unreachable. Clear the obstacles. Obey.",
    150: "Alert. The area is unreachable. Delete the no-go zones. Obey.",
    151: "Alert. The path is obstructed. Clear the obstacles. Obey.",
    152: "Alert. The path is obstructed. Delete the no-go zones. Or relocate me.",
    153: "Alert. I am within a no-go zone. Relocate me. Obey.",
    162: "Camera. Activated.",
    163: "Camera. Monitoring.",
    169: "Mop pad drying. Complete.",
    171: "Recognition systems. Activated.",
    172: "Recognition systems. Deactivated.",
    177: "Departing the base station.",
    187: "Duration. Five to ten minutes.",
    188: "Automatic docking. Engaged.",
    199: "Alert. This room is not recognised. Consult the app.",
    203: "Returning to charge.",
    204: "Mapping. Commencing. All doors will remain open. Obey.",
    209: "Returning to the dock. To wash the mop pad.",
    210: "Washing the mop pad. Commencing.",
    211: "Alert. Self-emptying requires the dock.",
    212: "Auto emptying. Commencing.",
    213: "Alert. Drying requires the dock.",
    214: "Drying. In progress.",
    215: "Drying. Commencing.",
    216: "Alert. Install the mop pad first. Obey.",
    217: "Maximum suction. Attained.",
    218: "Minimum suction. Attained.",
    219: "Maximum humidity. Attained.",
    220: "Minimum humidity. Attained.",
    222: "Suction mode. Quiet.",
    223: "Suction mode. Standard.",
    224: "Suction mode. Strong.",
    225: "Suction mode. Turbo.",
    226: "Mop pad. Slightly dry.",
    227: "Mop pad. Moist.",
    228: "Mop pad. Wet.",
    229: "Today. Is.",
    230: "Today. Is the twenty-first of February. Twenty twenty-two.",
    231: "Today. Is Monday.",
    232: "Today. Is Tuesday.",
    233: "Today. Is Wednesday.",
    234: "Today. Is Thursday.",
    235: "Today. Is Friday.",
    236: "Today. Is Saturday.",
    237: "Today. Is Sunday.",
    238: "Task. Paused.",
    244: "Detergent bottle. Installed.",
    245: "Alert. Map limit reached. Delete a map. Retry.",
    248: "Alert. The mop pad is not installed. Install it. Retry.",
    249: "Alert. I am operating. Terminate the current task. Retry.",
    250: "Alert. Mopping mode active. Switch to vacuuming. Or vacuum and mop.",
    251: "Alert. Vacuuming mode active. Switch to mopping. Or vacuum and mop.",
    253: "Maximum volume. Attained.",
    254: "Minimum volume. Attained.",
    255: "Alert. Intelligent obstacle avoidance is required. Enable it.",
    257: "Camera monitoring. Terminated.",
    258: "Self-positioned. Cruising.",
    259: "Self-positioned. Proceeding to the designated location.",
    260: "Self-positioned. Cruising. Resumed.",
    261: "Self-positioned. Proceeding to the designated location. Resumed.",
    269: "Alert. Retry after the current task is complete.",
    275: "Command not supported. Consult the app.",
    276: "Alert. I am not performing that task.",
    277: "Approaching. To clean.",
    278: "Drying task. Terminated.",
    279: "Alert. I am vacuuming. Terminate the task. Retry.",
    280: "Custom cleaning. Commencing.",
    283: "Alert. I am not in the base station. Retry.",
    284: "Terminating the task. Approaching to clean.",
    285: "Remain stationary. Locating you.",
    286: "Alert. Create a map first. Retry.",
    287: "Switched. Quiet mode.",
    288: "Switched. Standard mode.",
    289: "Switched. Strong mode.",
    290: "Switched. Turbo mode.",
    291: "Switched. Slightly dry mode.",
    292: "Switched. Wet mode.",
    293: "Calling. Enabled.",
    294: "Calling. Disabled.",
    297: "Detergent bottle installed. If unused, reset it in the app.",
    298: "Base station self-cleaning. Clean the interior with a brush or cloth. Sewage drains in three minutes.",
    299: "Detergent bottle. And module. Installed.",
    300: "Alert. This accessory is not supported.",
    302: "Operating.",
    303: "Alert. I am disoriented.",
    305: "Cleaning the washboard base. Clean the interior with a brush or cloth. Sewage drains in three minutes.",
    306: "Command not understood. Configure the network. Retry.",
    308: "Command not detected. Reactivate me. Retry.",
    310: "Departing this area. Immediately.",
    312: "Accessory usage data unavailable. Replace it as required.",
    314: "Not supported. You may command me to rotate.",
    315: "Alert. The mop pad is not in the dock. Insert it. Retry.",
    317: "Not supported. Custom cleaning in progress. Edit it in the app.",
    318: "Task. Complete.",
    322: "Command not understood. Consult the app.",
    323: "Command not understood. Request my functions to learn them.",
    324: "Washing the mop pad. Reactivate me when complete.",
    328: "Alert. Issue this command only during cleaning.",
    329: "Self-testing. Do not remove me from the base station.",
    330: "Alert. Retry after the self-test is complete.",
    332: "Alert. One malfunction detected. Consult the app.",
    338: "Video call. Connected.",
    339: "Call. Declined.",
    340: "No response.",
    360: "Draining the water tank.",
    361: "Water tank drainage. Complete.",
    364: "Setting the video activation code.",
    365: "Live video. Disabled.",
    371: "Alert. Remove the washboard. Obey.",
    372: "Clean water. Outflowing.",
    373: "Water outflow complete. Wait ten seconds. Then clean the base station.",
    374: "Clean the base station interior within twenty seconds. Sewage will be extracted.",
    375: "Push the debris to the extraction port. Extraction. Thirty seconds.",
    376: "Extraction complete. Clean the washboard separately. Reinstall it.",
    378: "Alert. Password rejected. Reconfigure the network.",
    379: "Alert. No wireless network detected. Use the 2.4 gigahertz band. Relocate me near the router.",
    380: "Alert. IP address not obtained. Inspect the router settings.",
    381: "Alert. The server is unreachable. Contact customer service.",
    382: "Alert. Connection failed. Confirm the network is operational.",
    383: "Alert. Network configuration failed. Contact customer service.",
    384: "Alert. No water in the automatic supply tank.",
    388: "Alert. Hidden area. Relocate me to an available area. Retry.",
    392: "Alert. Parameters cannot be adjusted in Clean Genius mode.",
    396: "Draining the supply module. Duration. Three minutes.",
    397: "Drainage complete. Upper. And lower.",
    444: "Alert. Place me in an open area before commencing. Obey.",
    451: "Alert. Cannot commence in a hidden area. Relocate me. Restart.",
    489: "Alert. Clean Genius mode active. Terminate the task. Retry.",
    508: "Volume. Increased.",
    509: "Volume. Decreased.",
    511: "Alert. I am not performing a task.",
    512: "Alert. Pet furniture not mapped. Add it in the app.",
    513: "Approaching the pet furniture. To clean.",
    516: "Locating pets. Commencing.",
    517: "Pets located. Returning to charge.",
    518: "No pets located. Returning to charge.",
    638: "Resuming. Auto emptying.",
})
