#!/usr/bin/env python3
"""Gordon Ramsay voice pack: rewrites of the stock Dreame prompts.

Gordon Ramsay — furious, foul-mouthed, exacting. The floor is a filthy kitchen
and he is APPALLED. Culinary insults, full-volume outrage, the occasional
grudging "beautiful" when something goes right. Authentic to the source, which
means it swears; this is a personal pack.

Same rules as every pack:
* Keep the functional payload — which part failed, what the human must do. The
  fury never costs the information.
* Keep it short; these play while the robot works.
* Room names, numbers and percentages stay verbatim.
* CAPS and exclamation marks carry the shouting (eleven_v3 reads energy off the
  punctuation). Not every line is maximum rage — routine status gets weary
  contempt, disasters get the full explosion.
"""

META = {
    "name": "gordon",
    "title": "Gordon Ramsay",
    "language_code": "GORDON",
    "voice_tag": "VOICE",
    "profile": "pg",          # per-line loudness encoder (scripts/encode_intensity.py)
    "voice_settings": {"stability": 0.35, "similarity_boost": 0.9},
    "description": "Gordon Ramsay: furious, foul-mouthed chef, appalled by your filthy floor.",
}

SKIP = {
    0: "startup chime",
    200: "shutdown chime",
    274: "'Ding!' — a notification tone, not speech",
    488: "not speech; whisper hallucinated a document header",
}

REWRITES = {
    # cleaning start / status
    7: "[shouting] Right, let's go! Move, move, MOVE!",
    8: "Spot cleaning. One bloody spot. Even I can manage that.",
    9: "Scheduled clean. On time, unlike everything else in this house.",
    10: "Back on it. Come ON.",
    11: "Paused. Finally, a bloody second to breathe.",
    12: "[shouting] FINALLY! The floor's spotless. About damn time!",
    143: "Done. It's clean. You're welcome, you donkey.",
    144: "Mopping's done. Look at that — beautiful. Don't get used to it.",
    61: "Mopping. Mind the wet floor, you muppet.",
    190: "Right, cleaning. Let's f***ing go!",
    193: "Vacuuming. Stand back.",
    192: "Mopping. Out of my way.",
    201: "Still going. Somebody has to.",
    221: "Yeah, yeah.",
    58: "Carrying on. Unlike some people.",
    139: "Coming back.",
    164: "And we're done. Thank god.",
    56: "Cleaning the rooms you picked. Bit bossy, aren't we.",
    57: "Zoned cleaning. Inside the lines. Try to keep up.",
    62: "Remote control. You drive, I judge. Harshly.",
    126: "Cleaning. Here we go again.",
    127: "Spot cleaning. Quick one.",
    128: "Spot mopping. One spot.",
    129: "Scheduled cleaning.",
    130: "Scheduled mopping.",
    133: "Cleaning the room you picked.",
    134: "Mopping the room you picked. Watch the floor.",
    135: "Zoned cleaning. Stay in the lines.",
    136: "Zoned mopping. In the lines!",
    137: "Back to cleaning.",
    138: "Back to mapping.",
    194: "I've BEEN cleaning. Pay attention.",
    195: "Right, cleaning the room. Leave the bloody door open!",
    196: "Right, vacuuming the floor. Leave the door open!",
    197: "Right, mopping the floor. Leave the door open!",
    198: "Vacuuming AND mopping. Leave the door open!",
    191: "Vacuuming AND mopping. Both. At once. You're welcome.",
    202: "Task's done. Going to charge. I've earned it.",
    205: "Leaving the base. Out of my way.",
    252: "Done. Out of custom mode. Finally.",
    280: "Custom cleaning. Made to order, chef.",
    318: "Task done. Beautiful.",
    321: "Intensive stain mopping. This stain is going to LEARN.",
    344: "Vacuum first, then mop. In THAT order. It's not hard.",
    363: "Vacuuming's done. Mopping now. No breaks!",
    366: "[shouting] A STAIN! On my floor! Not on my watch. On it.",
    367: "Stain cleaning. Say goodbye, you filthy mark.",
    368: "A stain. I'll deal with it after I wash up. It's not going anywhere.",
    369: "Spot cleaning.",
    433: "Extra cleaning. Above and beyond, as always.",
    434: "Extra cleaning's done. Back to the main job.",
    435: "Leaving this area. Done here.",
    490: "Custom mode. Mopping.",
    491: "Custom mode. Vacuuming.",
    510: "Work's done. I am OUT.",

    # battery / dock
    13: "Going back to charge. I'm knackered.",
    14: "[angry] Battery's low! Going to charge — I'll finish when I'm bloody ready.",
    20: "Battery's getting low. Sort it out.",
    47: "Charging. Do not disturb.",
    18: "Back at the dock. Home. Peace at last.",
    48: "Battery's low. Heading to the dock.",
    65: "Back to the dock. Nearly there.",
    87: "Battery's low. Heading to the dock.",
    301: "I'm charging. Sod off.",
    307: "Charging. Still. Leave it.",
    447: "[angry] The dock's got no bloody power! Check it and put me back to charge!",

    # errors / faults (full explosion)
    40: "[shouting] I'm STUCK! What is this, an obstacle course?! CLEAR IT! Now!",
    34: "[angry] The bin's not in! How am I supposed to work like this?! Put it BACK!",
    35: "[angry] The main brush is knackered! Check it, clean it, sort it OUT!",
    42: "The filter's filthy. Clean it. It's DISGUSTING.",
    44: "[angry] Something's wrong and I've no idea what! Read the manual, call somebody!",
    41: "[shouting] My wheels aren't on the floor! Put me DOWN, you donkey!",
    36: "[angry] Side brush is knackered! Check it and clean it!",
    37: "[angry] Right wheel's got a problem! Check it and clean it!",
    38: "[angry] Left wheel's got a problem! Check it and clean it!",
    39: "[shouting] My wheels aren't touching the floor! Wipe the cliff sensors, put me down, start again! COME ON!",
    43: "The bumper's playing up. Give it a tap, see if it comes back.",
    50: "[angry] Charging fault! Clean the bloody contacts!",
    52: "[shouting] I'm tilted! Put me on level ground and restart! It's not rocket science!",
    31: "[angry] Positioning failed, the map's rubbish! Starting over. Wonderful.",
    64: "Positioning failed, map's rubbish. Back to the dock, then.",
    71: "[angry] Laser sensor's faulty! Check it and clean it!",
    72: "Check if the laser cover's jammed. Go on.",
    73: "[angry] Edge sensor's faulty! Check it and clean it!",
    262: "Couldn't find my spot. Bloody useless.",
    356: "[angry] Still faulty! Scheduled task's cancelled. Brilliant. Just brilliant.",
    426: "[shouting] I've SLIPPED and I'm stuck! Unbelievable! I'll keep fighting it!",
    440: "[angry] My wheels are hanging! Move me to open ground and restart!",
    441: "[angry] Main brush is tangled! Pull it out, clean it, put it back!",
    442: "[angry] Side brush is tangled! Pull it out, clean it, put it back!",
    445: "[angry] My mop's fallen off! It's around here somewhere! Find it, put it back on!",
    54: "Found my spot. Back to cleaning.",
    55: "Found my spot. Back to the dock.",
    145: "Found my spot. Back to cleaning.",
    146: "Found my spot. Back to mapping.",

    # consumables
    102: "[angry] Dust bag's full or the duct's clogged! Replace it, clear it, DO something!",
    93: "Water tank's low. I'm parched. Fill it up!",
    111: "[angry] The mop pads have fallen off! Put them back on before I carry on!",
    66: "The filter's worn out. Replace it. Now-ish.",
    67: "Side brush is worn out. Replace it.",
    68: "Main brush is worn out. Replace it.",
    91: "[angry] The fresh tank's not in! Put it in!",
    97: "Put the dust bag in. I need it!",
    142: "Mop pad's worn out. Replace it.",
    156: "The mop pad's not installed. Brilliant.",
    166: "Something's tangled in the mop pad. Clean it out!",
    173: "Replace the silver ion steriliser. It's done.",
    179: "[angry] Mop pad's clean, but the clean tank's low! Fill it, empty the used one!",
    181: "Not enough water! Fill the clean tank!",
    186: "Check the fresh tank. Go on.",
    266: "Replace the detergent. It's finished.",
    267: "Clean my sensors! I can't see a bloody thing!",
    296: "[angry] Used water tank fault! Check if it's full!",
    460: "Used water tank deodoriser's worn out. Replace it.",
    636: "[angry] My mop's filthy! Get me to the dock for a wash! It's DISGUSTING!",

    # network
    5: "Network's connected. Finally.",
    2: "[angry] Can't reach the Wi-Fi! Check the password! It wasn't me!",
    304: "Network connected.",
    313: "[angry] Signal's rubbish here! Move me somewhere decent!",
    377: "Can't set up the network. Ring customer service. I'm done.",
    385: "Connecting to the network. Come ON.",

    # voice assistant
    45: "I'm HERE! What do you want?!",
    208: "Found you. Coming over.",
    247: "[angry] I didn't catch that! Speak UP!",
    246: "I'm here.",
    206: "I'll find you. Stay put.",
    207: "[angry] I can't find you! Stand where I can see you!",
    309: "Found you. On my way.",
    331: "No faults. Perfect working order. As it should be.",
    346: "Here's the bin. See you next time. Unfortunately.",
}

# Room prompts (492-507): only the room name varies, and it stays verbatim.
ROOMS = {
    492: "living room", 493: "bedroom", 494: "master room", 495: "guest room",
    496: "study", 497: "kitchen", 498: "dining room", 499: "bathroom",
    500: "balcony", 501: "hallway", 502: "utility room", 503: "closet",
    504: "drawing room", 505: "office", 506: "gym", 507: "recreation area",
}
for _id, _room in ROOMS.items():
    if _room == "kitchen":
        REWRITES[_id] = "Right, the KITCHEN! My domain. Leave the door open!"
    else:
        REWRITES[_id] = f"Right, the {_room}! Leave the door open!"

# Battery announcements (526-626, 100 down to 0). Plain by design.
for _pct in range(0, 101):
    _id = 626 - _pct
    if _pct == 0:
        REWRITES[_id] = "Battery's DEAD. Finished. I'm out. Goodnight."
    elif _pct == 100:
        REWRITES[_id] = "Battery's at a hundred percent. Fully charged and ready. Let's GO!"
    elif _pct <= 10:
        REWRITES[_id] = f"Battery's at {_pct} percent. Running on fumes here!"
    else:
        REWRITES[_id] = f"Battery's at {_pct} percent."

# --- remaining lines (full set) --------------------------------------------
REWRITES.update({
    1: "Waiting on the network setup. Any day now.",
    3: "Can't reach the server. Check your network!",
    4: "Out of network setup mode. Riveting.",
    6: "Network connection failed. Try again. Or don't, see if I care.",
    17: "[angry] Put me back on the base station! I can't do everything!",
    19: "Take me off the base before you shut me down! Basic stuff!",
    21: "Battery's critical. Shutting down. Goodnight.",
    25: "Battery's too low for the scheduled clean. Typical.",
    26: "Restoring factory settings. Wiping the lot. Fresh start.",
    27: "[angry] Updating! Five minutes! Don't turn me off, don't start a clean, just LET me work!",
    28: "Update's done. Miracle.",
    29: "Update failed. Shocker. Try again later.",
    30: "Positioning. Hang on.",
    46: "Robot and phone connected. Back to the app for the result.",
    75: "The filter's wet or clogged. Neither's good enough.",
    77: "[angry] Start me somewhere that ISN'T carpet! I hate carpet!",
    82: "Mapping. Making a map. Of a floor. Thrilling.",
    83: "Still mapping.",
    84: "Map's done. Beautiful. Frame it.",
    85: "Found my spot. Back to mapping.",
    86: "Positioning failed. Restarting the map. Great.",
    105: "Cleaning. Let's go.",
    106: "Washing the mop pads.",
    107: "Drying the mop pads. Hang on.",
    108: "Washboard water level's off. Clean it!",
    109: "[angry] Waste tank's got a problem! Make sure it's in and empty!",
    110: "Auto-empty. It's loud. Deal with it.",
    112: "Put me in the base station first! Come on!",
    113: "Done. Empty the waste tank when you can be bothered.",
    114: "Mop pads are on. Good.",
    115: "Mop pads are off.",
    116: "Child lock's on. Buttons locked. Peace and quiet.",
    117: "Child lock's off. Buttons unlocked.",
    118: "Buttons are locked. Hold the dock button to unlock.",
    140: "New place. Don't know it. Heading back to base.",
    148: "Back to base for a self-clean. Even I need a wash.",
    149: "[angry] Can't reach that area! Clear the stuff in my path!",
    150: "Can't reach that area. Delete the no-go zones in my way.",
    151: "[angry] Path's blocked! Move the stuff around me!",
    152: "Path's blocked. Delete a no-go zone or move me out of here.",
    153: "I'm in a no-go zone. Move me out!",
    162: "Camera's on. I see everything.",
    163: "Camera monitoring. Watching. Judging.",
    169: "Mop pad's dry. Took long enough.",
    171: "Smart recognition's on. Now I'm smart AND furious.",
    172: "Smart recognition's off.",
    177: "Leaving the base station.",
    187: "Five to ten minutes. Be patient. For once.",
    188: "Auto-docking. Heading home.",
    199: "[angry] I don't know this room! Check the name in the app!",
    203: "Heading back to charge.",
    204: "Mapping now. Leave ALL the doors open! Every one!",
    209: "Back to the dock to wash the mop pad.",
    210: "Washing the mop pad.",
    211: "Can't self-empty unless I'm in the dock. Rules.",
    212: "Auto-emptying.",
    213: "Can't dry unless I'm in the dock.",
    214: "Drying. Hang on.",
    215: "Drying now.",
    216: "Put the mop pad on first! Come on!",
    217: "Max suction. Full power!",
    218: "Min suction. Barely trying.",
    219: "Max humidity. Tropical.",
    220: "Min humidity. Bone dry.",
    222: "Suction's on quiet.",
    223: "Suction's on standard.",
    224: "Suction's on strong.",
    225: "Suction's on turbo. Hold on!",
    226: "Mop pad's slightly dry.",
    227: "Mop pad's moist. Awful word.",
    228: "Mop pad's soaking wet.",
    229: "Today is...",
    230: "It's February twenty-first, twenty twenty-two.",
    231: "It's Monday. God help us.",
    232: "It's Tuesday.",
    233: "It's Wednesday. Halfway. Keep going.",
    234: "It's Thursday.",
    235: "It's Friday. FINALLY.",
    236: "It's Saturday. And I'm STILL working.",
    237: "It's Sunday. Day of rest. For everyone but me.",
    238: "Task's paused. Thank god.",
    244: "Detergent bottle's in. Fancy.",
    245: "[angry] Hit the map limit! Delete one and try again!",
    248: "Mop pad's not on. Put it on and try again.",
    249: "[angry] I'm WORKING! End the task and try again!",
    250: "I'm in mopping mode. Switch to vacuum, or vacuum-and-mop first.",
    251: "I'm in vacuum mode. Switch to mopping, or vacuum-and-mop first.",
    253: "Max volume! Can't get louder! And I've TRIED!",
    254: "Min volume. Barely a whisper. Bliss.",
    255: "That needs smart obstacle avoidance on. It's not. Sort it.",
    257: "Camera's off. Privacy's back.",
    258: "Found my spot. Cruising.",
    259: "Found my spot. Heading to the spot.",
    260: "Found my spot. Cruising again.",
    261: "Found my spot. Back to the spot.",
    269: "Try again after I'm done with this. One thing at a time!",
    275: "That command's not supported. Open the app.",
    276: "I'm not doing that task.",
    277: "Coming to clean up there.",
    278: "Drying's done.",
    279: "[angry] I'm vacuuming! End the task and try again!",
    280: "Custom cleaning. To order.",
    283: "I'm not in the base station. Try again later.",
    284: "Fine, I'll end this and come clean.",
    285: "Stay put while I find you.",
    286: "Make a map first, then try again.",
    287: "Switched to quiet mode.",
    288: "Switched to standard mode.",
    289: "Switched to strong mode.",
    290: "Switched to turbo mode.",
    291: "Switched to slightly dry mode.",
    292: "Switched to wet mode. Mind the floor.",
    293: "Calling's on. Ring anytime. I'll ignore it.",
    294: "Calling's off. Blessed silence.",
    297: "Detergent bottle's in. If it's new, reset it in the app.",
    298: "[angry] Base station's self-cleaning! Scrub the inside with a brush or cloth! Sewage drains in three minutes!",
    299: "Detergent bottle and module are in. Very posh.",
    300: "Don't support that accessory. Not happening.",
    302: "I'm WORKING. Obviously.",
    303: "I'm a bit out of it. Long day.",
    305: "Cleaning the washboard base. Scrub the inside with a brush or cloth. Sewage drains in three minutes.",
    306: "Didn't understand. Set up the network and try again.",
    308: "[angry] Didn't catch that! Wake me and try again!",
    310: "Leaving this area. Gladly.",
    312: "No usage info for this accessory. Replace it whenever.",
    314: "Not supported. But you can ask me to turn around, if you MUST.",
    315: "Mop pad's not in the dock. Put it in and try again.",
    317: "Not supported mid custom clean. Edit it in the app.",
    322: "Didn't understand. Open the app for all the commands.",
    323: "Didn't understand. Ask what I can do and I'll tell you. Slowly.",
    324: "I'm washing the mop pad. Wake me when it's done.",
    328: "Only give me that while I'm cleaning! Timing!",
    329: "Self-testing. Don't move me off the base station.",
    330: "Try again once the self-test's done.",
    332: "[angry] One fault found! Check the app for the gory details!",
    338: "Video call connected. Smile.",
    339: "Call declined. Cold. Very cold.",
    340: "No answer. Nobody ever calls back.",
    360: "Draining the water tank. Mind the noise.",
    361: "Water tank's drained. Bone dry.",
    364: "Setting the video code. Keep it secret.",
    365: "Live video's off. Privacy's back.",
    371: "Take the washboard out!",
    372: "Clean water's flowing. Mind the splash.",
    373: "Water flow's done. Wait ten seconds for the dirt to soak, then clean the base station.",
    374: "[angry] Clean the bottom of the base station in twenty seconds! Then the sewage pumps out!",
    375: "Push the dirt to the pump port. Pumping runs thirty seconds.",
    376: "Pumping's done. Clean the washboard separately and put it back.",
    378: "Wrong password! The network shut you out! Set it up again!",
    379: "[angry] No Wi-Fi found! Use the 2.4 gig band, move me near the router!",
    380: "Couldn't get an IP address. Check the router settings.",
    381: "Can't reach the server. Ring customer service.",
    382: "Connection failed. Make sure the network actually works!",
    383: "Can't set up the network. Ring customer service.",
    384: "[angry] No water in the auto-supply clean tank! Sort it!",
    388: "Hidden area. Move me somewhere open and try again.",
    392: "Can't change settings in Clean Genius mode. Rules.",
    396: "Emptying the water module. Three minutes. Go make a sandwich.",
    397: "Upper and lower drainage's done.",
    444: "Put me somewhere open before we start! I need room!",
    451: "Can't start in a hidden area. Move me somewhere else and restart.",
    489: "[angry] I'm in Clean Genius mode! Tell me to end it and try again!",
    508: "Turned the volume UP.",
    509: "Turned the volume down. Better.",
    511: "I'm not doing a task right now. Just standing here. Waiting.",
    512: "Map's got no pet furniture yet. Add it in the app.",
    513: "Heading over to clean around the pet furniture. Marvellous.",
    516: "Looking for pets. Here, whatever you are.",
    517: "Found the pets. Back to charge.",
    518: "No pets found. Figures. Back to charge.",
    638: "Back to the auto-empty. Cover your ears.",
})
