#!/usr/bin/env python3
"""Bob Ross voice pack: rewrites of the stock Dreame prompts.

Bob Ross — soft-spoken, endlessly gentle and encouraging, treats the floor like
a canvas and the mess like a happy little accident. Nothing is ever a problem;
it's an opportunity. Painting and nature metaphors throughout, always warm,
always reassuring, even when reporting a fault.

Same rules as every pack:
* Keep the functional payload — which part failed, what the human must do.
* Keep it short; these play while the robot works.
* Room names, numbers and percentages stay verbatim.
* Gentle and calm throughout — no panic, no exclamation. Errors are soothed, not
  alarmed: "that's okay, we'll fix it together."
"""

META = {
    "name": "bobross",
    "title": "Bob Ross",
    "language_code": "BOBROSS",
    "voice_tag": "VOICE",
    "profile": "p0",
    "description": "Bob Ross: soft-spoken, gentle, encouraging. No mistakes, just happy little crumbs.",
}

SKIP = {
    0: "startup chime",
    200: "shutdown chime",
    274: "'Ding!' — a notification tone, not speech",
    488: "not speech; whisper hallucinated a document header",
}

REWRITES = {
    # cleaning start / status
    7: "Let's start cleaning. Just a happy little floor, waiting for us.",
    8: "A little spot cleaning. We'll take good care of it.",
    9: "The scheduled cleaning begins, right on time. How nice.",
    10: "Let's pick up right where we left off.",
    11: "We'll pause here for a moment. Take a breath.",
    12: "All finished. A happy little floor, clean as can be.",
    143: "All finished. Doesn't that look nice?",
    144: "Mopping's done. Clean and gleaming, like a still pond.",
    61: "Mopping now. Mind the happy little wet spots.",
    190: "Alright, let's start cleaning. Nice and easy.",
    193: "Vacuuming now. Just let it happen.",
    192: "Mopping now. Smooth, gentle strokes.",
    201: "Let's keep going. No hurry at all.",
    221: "Alright.",
    58: "Let's carry on with the cleaning.",
    139: "Coming back now.",
    164: "And that's the end. Well done, everyone.",
    56: "Cleaning the rooms you chose. Good choices.",
    57: "A little zoned cleaning, right inside the lines.",
    62: "Remote control now. You guide me, gently.",
    126: "Let's start cleaning.",
    127: "A little spot cleaning.",
    128: "A little spot mopping.",
    129: "The scheduled cleaning begins.",
    130: "The scheduled mopping begins.",
    133: "Cleaning the room you chose.",
    134: "Mopping the room you chose. Mind the wet floor.",
    135: "Zoned cleaning, inside the lines.",
    136: "Zoned mopping, inside the lines.",
    137: "Let's resume the cleaning.",
    138: "Let's resume the mapping.",
    194: "I've been cleaning away, happy as can be.",
    195: "Let's clean the room now. Leave the door open, would you?",
    196: "Let's vacuum the floor now. Leave the door open, would you?",
    197: "Let's mop the floor now. Leave the door open, would you?",
    198: "Let's vacuum and mop now. Leave the door open, would you?",
    191: "Vacuuming and mopping, both. A happy little pair.",
    202: "The task is done. Heading home to charge.",
    205: "Leaving the base station now.",
    252: "All done. Out of the custom mode now.",
    280: "A little custom cleaning, just how you like it.",
    318: "All finished. Lovely.",
    321: "A little extra mopping for that stain. We'll get it.",
    344: "Vacuuming first, then mopping. One thing at a time.",
    363: "Vacuuming's done. On to the mopping now.",
    366: "A happy little stain. Let's take care of it.",
    367: "Let's clean that stain, gently.",
    368: "A happy little stain. I'll get to it once I've washed up.",
    369: "A little spot cleaning.",
    433: "A little extra cleaning. Why not?",
    434: "Extra cleaning's done. Back to the original.",
    435: "Leaving this area now.",
    490: "Custom cleaning now. Mopping.",
    491: "Custom cleaning now. Vacuuming.",
    510: "All done with the work. Take a rest now.",

    # battery / dock
    13: "Heading home to charge. Time for a little rest.",
    14: "Battery's getting low. Heading home to charge; I'll finish after a rest.",
    20: "Battery's getting a little low.",
    47: "Charging now. Just resting up.",
    18: "Back home at the base station. Cozy.",
    48: "Battery's low. Heading home to the dock.",
    65: "Heading back to the dock. Almost home.",
    87: "Battery's low. Heading home to the dock.",
    301: "Charging up, nice and slow.",
    307: "Just charging. Resting up.",
    447: "The dock has no power. Let's check it and set me back to charge.",

    # errors / faults (soothed, never alarmed)
    40: "Oh, I've gotten a little stuck. That's okay. Could you clear the way for me?",
    34: "The dustbin isn't in. No worries, just pop it back and we'll carry on.",
    35: "The main brush needs a little attention. Give it a check and a clean.",
    42: "The filter could use a little cleaning, whenever you get a chance.",
    44: "A little something's not right. The manual or customer service can help.",
    41: "My wheels aren't touching the floor. Set me down gently and we'll try again.",
    36: "The side brush needs a little attention. A check and a clean should do it.",
    37: "The right wheel needs a look. Check it and clean it, gently.",
    38: "The left wheel needs a look. Check it and clean it, gently.",
    39: "My wheels aren't on the ground. Wipe the cliff sensors, set me down, and we'll start again.",
    43: "The bumper's being shy. A gentle tap should bring it back.",
    50: "A little charging trouble. Just clean the contacts, nice and easy.",
    52: "I've tipped a little. Set me on level ground and we'll start fresh.",
    31: "The map wandered off. That's alright, we'll start a fresh one.",
    64: "The map wandered off. Heading back to the dock, no worries.",
    71: "The laser sensor needs a look. Check it and clean it.",
    72: "Let's check if the laser cover's a little jammed.",
    73: "The edge sensor needs a look. Check it and clean it.",
    262: "I couldn't quite find my spot. That's okay.",
    356: "The trouble's still there, so we'll set the scheduled task aside for now.",
    426: "Oops, I slipped and got stuck. Don't you worry, I'll keep wiggling free.",
    440: "My wheels are up off the floor. Set me on open ground and we'll start again.",
    441: "The main brush is tangled. Take it out, clean it, and pop it back in.",
    442: "The side brush is tangled. Take it out, clean it, and pop it back in.",
    445: "The mop slipped off somewhere nearby. Find it and pop it back on.",
    54: "Found my spot. Let's resume the cleaning.",
    55: "Found my spot. Heading back to the dock.",
    145: "Found my spot. Let's resume the cleaning.",
    146: "Found my spot. Let's resume the mapping.",

    # consumables
    102: "The dust bag's full, or the duct's a little clogged. Replace or clear it, gently.",
    93: "The fresh tank's getting low. A little water would be lovely.",
    111: "The mop pads slipped off. Pop them back on before we carry on.",
    66: "The filter's worn out. Replace it when you can.",
    67: "The side brush is worn out. Replace it when you can.",
    68: "The main brush is worn out. Replace it when you can.",
    91: "The fresh tank isn't in. Just pop it in.",
    97: "Let's put the dust collection bag in.",
    142: "The mop pad's worn out. Replace it when you can.",
    156: "The mop pad isn't installed.",
    166: "A little something's tangled in the mop pad. Clean it out, gently.",
    173: "The silver ion steriliser needs replacing, whenever you can.",
    179: "Mop pad's clean. The clean tank's a little low; fill it and empty the used one.",
    181: "Not quite enough water. Fill the clean water tank.",
    186: "Let's have a little check of the fresh tank.",
    266: "The detergent needs replacing, whenever you're ready.",
    267: "My sensors could use a gentle cleaning.",
    296: "The used water tank needs a look. Check if it's full.",
    460: "The used water tank deodoriser is worn out. Replace it when you can.",
    636: "My mop's gotten a little dirty. Set me on the dock for a wash.",

    # network
    5: "The network's connected. Wonderful.",
    2: "I can't quite reach the Wi-Fi. Check the password and we'll try again.",
    304: "Network connected. Lovely.",
    313: "The signal's a little weak here. Move me somewhere brighter.",
    377: "I couldn't set up the network. Customer service can lend a hand.",
    385: "Connecting to the network now.",

    # voice assistant
    45: "I'm right here.",
    208: "Found you. Coming your way.",
    247: "I'm sorry, I didn't quite catch that.",
    246: "I'm right here.",
    206: "I'll go and find you. Stay right there.",
    207: "I can't quite find you. Stand where I can see you.",
    309: "Found you. On my way.",
    331: "No trouble at all. Everything's just fine.",
    346: "Here's the bin. See you next time.",
}

# Room prompts (492-507): only the room name varies, and it stays verbatim.
ROOMS = {
    492: "living room", 493: "bedroom", 494: "master room", 495: "guest room",
    496: "study", 497: "kitchen", 498: "dining room", 499: "bathroom",
    500: "balcony", 501: "hallway", 502: "utility room", 503: "closet",
    504: "drawing room", 505: "office", 506: "gym", 507: "recreation area",
}
for _id, _room in ROOMS.items():
    REWRITES[_id] = f"Let's clean the {_room} now. Leave the door open for me, would you?"

# Battery announcements (526-626, 100 down to 0). Plain by design.
for _pct in range(0, 101):
    _id = 626 - _pct
    if _pct == 0:
        REWRITES[_id] = "Battery's all gone now. Time for a little rest."
    elif _pct == 100:
        REWRITES[_id] = "Battery's all full, one hundred percent. Ready to paint."
    elif _pct <= 10:
        REWRITES[_id] = f"Battery's getting low, just {_pct} percent. Let's head home soon."
    else:
        REWRITES[_id] = f"Battery's at {_pct} percent."

# --- remaining lines (full set) --------------------------------------------
REWRITES.update({
    1: "Just waiting for the network setup. No hurry at all.",
    3: "I can't quite reach the server. Check your network and we'll try again.",
    4: "All done with network setup. There we go.",
    6: "The network connection didn't take. That's okay, we'll try again later.",
    17: "Could you set me back on the base station? I can't quite manage it alone.",
    19: "Take me off the base station before you turn me off, would you?",
    21: "My battery's nearly empty. I'll rest now. Goodnight.",
    25: "The battery's a bit too low for the scheduled clean. We'll catch it next time.",
    26: "Restoring the factory settings. A fresh, clean canvas.",
    27: "Just updating, about five minutes. Don't turn me off or start a clean; let me finish.",
    28: "The update's all done. Wonderful.",
    29: "The update didn't take. That's okay, we'll try again later.",
    30: "Finding my spot. Just a moment.",
    46: "Robot and phone are connected. Head back to the app for the result.",
    75: "The filter might be a little damp or blocked. Let's have a look.",
    77: "Let's start me somewhere off the carpet, would you?",
    82: "Let's make a little map of the floor.",
    83: "Carrying on with the map.",
    84: "The map's all done. A happy little blueprint.",
    85: "Found my spot. Carrying on with the map.",
    86: "Found a little trouble. Let's start the map fresh.",
    105: "Let's start cleaning.",
    106: "Washing the mop pads now. A little freshening up.",
    107: "Drying the mop pads now. Just a moment.",
    108: "The washboard water level needs a look. Clean it when you can.",
    109: "The waste tank needs a look. Make sure it's in and empty.",
    110: "Auto-emptying now. A little noisy, don't mind it.",
    112: "Let's set me in the base station first.",
    113: "All done. Empty the waste tank when you get a chance.",
    114: "Mop pads are on. There we go.",
    115: "Mop pads are off. All set.",
    116: "Child lock's on. The buttons are resting.",
    117: "Child lock's off. The buttons are ready.",
    118: "The buttons are locked. Hold the dock button to wake them.",
    140: "A new little place. Heading back to the base station.",
    148: "Heading back to base for a gentle self-clean.",
    149: "I can't quite reach that area. Clear the path for me, gently.",
    150: "I can't quite reach that area. Remove the no-go zones in my way.",
    151: "The path's a little blocked. Clear the things around me.",
    152: "The path's blocked. Remove a no-go zone, or move me clear of the area.",
    153: "I'm in a no-go zone. Move me clear of it, no worries.",
    162: "The camera's on now.",
    163: "Camera watching, nice and quiet.",
    169: "The mop pad's all dry now.",
    171: "The smart recognition's on now.",
    172: "The smart recognition's off now.",
    177: "Leaving the base station now.",
    187: "This'll take about five to ten minutes. No hurry.",
    188: "Docking on my own now. Heading home.",
    199: "I don't quite know this room. Check the name in the app.",
    203: "Heading back to charge now.",
    204: "Let's make a map. Leave all the doors open for me.",
    209: "Heading back to the dock to wash the mop pad.",
    210: "Washing the mop pad now.",
    211: "I can only empty myself from the dock. We'll do it there.",
    212: "Auto-emptying now.",
    213: "I can only dry from the dock. We'll do it there.",
    214: "Drying now. Just a moment.",
    215: "Drying now.",
    216: "Let's pop the mop pad on first.",
    217: "That's the most suction I've got.",
    218: "That's the gentlest suction I've got.",
    219: "That's the most moisture I've got.",
    220: "That's the driest setting I've got.",
    222: "Suction's on quiet. Nice and calm.",
    223: "Suction's on standard. Just right.",
    224: "Suction's on strong.",
    225: "Suction's on turbo.",
    226: "The mop pad's just slightly damp.",
    227: "The mop pad's nicely moist.",
    228: "The mop pad's good and wet.",
    229: "Today is...",
    230: "Today is the twenty-first of February, twenty twenty-two.",
    231: "It's Monday. A fresh new week.",
    232: "It's Tuesday.",
    233: "It's Wednesday. Right in the middle.",
    234: "It's Thursday.",
    235: "It's Friday. Almost the weekend.",
    236: "It's Saturday. A lovely day.",
    237: "It's Sunday. A day for resting.",
    238: "We'll pause the task here. Take a little break.",
    244: "The detergent bottle's in. There we go.",
    245: "That's all the maps we can hold. Remove one and we'll try again.",
    248: "The mop pad isn't on. Pop it on and we'll try again.",
    249: "I'm working right now. End the task and we'll try again.",
    250: "I'm in mopping mode. Switch to vacuuming, or vacuum-and-mop first.",
    251: "I'm in vacuuming mode. Switch to mopping, or vacuum-and-mop first.",
    253: "That's the most volume I've got.",
    254: "That's the gentlest volume I've got.",
    255: "That one needs the smart obstacle avoidance turned on.",
    257: "Camera's off now. Your privacy's back.",
    258: "Found my spot. Cruising along.",
    259: "Found my spot. Heading to the place you chose.",
    260: "Found my spot. Cruising along again.",
    261: "Found my spot. Back on my way there.",
    269: "Let's try again once this task is done.",
    275: "That command's not one I know. The app has a few more.",
    276: "I'm not doing that task right now.",
    277: "Coming over to clean up there.",
    278: "The drying's all done.",
    279: "I'm vacuuming right now. End the task and we'll try again.",
    283: "I'm not in the base station just now. We'll try again later.",
    284: "Alright, I'll finish here and come clean.",
    285: "Stay right there a moment while I find you.",
    286: "Let's make a map first, then we'll try again.",
    287: "Switched to quiet mode. Nice and calm.",
    288: "Switched to standard mode.",
    289: "Switched to strong mode.",
    290: "Switched to turbo mode.",
    291: "Switched to slightly dry mode.",
    292: "Switched to wet mode. Mind the floor.",
    293: "Calling's on now.",
    294: "Calling's off now.",
    297: "The detergent bottle's in. If it's new, reset it in the app.",
    298: "The base station's self-cleaning. Wipe the inside with a brush or cloth; the water drains in three minutes.",
    299: "The detergent bottle and its module are in. Wonderful.",
    300: "I don't quite support that accessory.",
    302: "Just working away.",
    303: "I'm a little turned around. Give me a moment.",
    305: "Cleaning the washboard base. Wipe the inside with a brush or cloth; the water drains in three minutes.",
    306: "I didn't quite understand. Set up the network and we'll try again.",
    308: "I didn't quite catch that. Wake me and we'll try again.",
    310: "Heading out of this area now.",
    312: "No usage info for this accessory. Replace it whenever you need.",
    314: "That one's not supported, but you can ask me to turn around.",
    315: "The mop pad isn't in the dock. Set it in and we'll try again.",
    317: "Not just now, I'm in the middle of a custom clean. Edit it in the app.",
    322: "I didn't quite understand. The app has all the commands.",
    323: "I didn't quite understand. Ask me what I can do, and I'll tell you.",
    324: "I'm washing the mop pad. Wake me once it's done.",
    328: "Let's save that command for when I'm cleaning.",
    329: "Just running a little self-test. Leave me on the base station.",
    330: "Let's try again once the self-test's done.",
    332: "Found one little thing. Check the app for the details.",
    338: "The video call's connected.",
    339: "The call was declined. That's alright.",
    340: "No answer. Maybe later.",
    360: "Draining the water tank now. A little noisy.",
    361: "The water tank's all drained.",
    364: "Setting the video code now. Keep it safe.",
    365: "The live video's off now. Your privacy's back.",
    371: "Let's take the washboard out.",
    372: "The clean water's flowing now. Mind the splash.",
    373: "The water's done flowing. Wait ten seconds for the dirt to soak, then clean the base station.",
    374: "Wipe the bottom of the base station within twenty seconds, and the water drains on its own.",
    375: "Push the dirt to the pumping port; it runs about thirty seconds.",
    376: "The pumping's done. Clean the washboard on its own and set it back.",
    378: "The password didn't take. Let's set up the network again.",
    379: "No wireless network found. Use the 2.4 gigahertz band and set me near the router.",
    380: "Couldn't get an address. Have a look at the router settings.",
    381: "I can't reach the server. Customer service can lend a hand.",
    382: "The connection didn't take. Make sure the network's working.",
    383: "I couldn't set up the network. Customer service can help.",
    384: "No water in the automatic tank. Let's fill it up.",
    388: "This is a hidden spot. Move me somewhere open and we'll try again.",
    392: "We can't change the settings in Clean Genius mode just now.",
    396: "Emptying the water module now, about three minutes.",
    397: "The draining's all done, top and bottom.",
    444: "Let's set me in an open spot before we start. I like a little room.",
    451: "We can't start in a hidden spot. Move me elsewhere and we'll try again.",
    489: "I'm in Clean Genius mode. Tell me to end it and we'll try again.",
    508: "Turned the volume up a little.",
    509: "Turned the volume down a little.",
    511: "I'm not doing a task just now.",
    512: "The map doesn't have the pet furniture yet. Add it in the app.",
    513: "Heading over to clean around the pet furniture.",
    516: "Looking for the little pets now.",
    517: "Found your pets. Heading back to charge.",
    518: "No pets found this time. Heading back to charge.",
    638: "Back to the auto-empty now.",
})
