#!/usr/bin/env python3
"""Bertram voice pack (Disney's Jessie): rewrites of the stock Dreame prompts.

Bertram is the Ross family's butler — lazy, deadpan, sardonic, perpetually
unimpressed, and doing this entire job under protest. The register: dry,
reluctant, weary sarcasm. He'll tell you what's wrong and what to do, but he
wants you to know he'd rather be watching his shows or making a sandwich.

Same rules as every pack:
* Keep the functional payload — which part failed, what the human must do.
* Keep it short; these play while the robot works.
* Room names, numbers and percentages stay verbatim.
* Deadpan, not shouty. The comedy is in the flat, put-upon delivery, so the
  text is understated — few exclamation marks. He's too tired to yell.

DRAFT for review: high-traffic prompts and one of each category, plus the room
and battery templates in full. Remaining lines held until voice + direction are
approved.
"""

META = {
    "name": "bertram",
    "title": "Bertram",
    "language_code": "BERTRAM",
    "voice_tag": "CLONE",
    "profile": "p0",           # natural voice, no processing
    "description": "Bertram from Jessie: lazy, deadpan, sardonic butler doing this under protest.",
}

SKIP = {
    0: "startup chime",
    200: "shutdown chime",
    274: "'Ding!' — a notification tone, not speech",
    488: "not speech; whisper hallucinated a document header",
}

REWRITES = {
    # --- cleaning start / status -----------------------------------------
    7: "Ugh, fine. Cleaning. Whatever.",
    8: "Spot cleaning. One spot. I can handle one spot.",
    9: "Scheduled cleaning. Yes, I remembered. Unfortunately.",
    10: "Back to it, I guess.",
    11: "Paused. Finally, a break.",
    12: "There. It's clean. Can I go now?",
    143: "Done. It's clean. You're welcome.",
    144: "Mopping's done. My back hurts.",
    61: "Mopping. Try not to walk on it, geniuses.",
    190: "Yeah, yeah, cleaning. Here we go.",
    193: "Vacuuming. The dream I always had.",
    192: "Mopping. Living the life.",
    201: "Still going. Somehow.",
    221: "Fine.",
    58: "Continuing. Reluctantly.",
    139: "Coming back.",
    164: "And we're done. Thank goodness.",

    # --- battery / dock --------------------------------------------------
    13: "Heading back to charge. I'm exhausted.",
    14: "Battery's low. Going to charge. I'll finish later. Maybe.",
    20: "Battery's low. Honestly? Same.",
    47: "Charging. Don't bother me.",
    18: "Back at the dock. Ah, home.",

    # --- errors / faults (weary complaint, not panic) --------------------
    40: "Great. I'm stuck. This is exactly how I pictured my afternoon. Clear the way, would ya?",
    34: "The dustbin's not in. I can't work like this. Put it back.",
    35: "Main brush is acting up. Check it and clean it. Or don't. I'm not your boss.",
    42: "Filter needs cleaning. Add it to the list.",
    44: "Something's wrong. No idea what. Read the manual, call somebody.",
    41: "My wheels aren't on the floor. Put me down. Please.",

    # --- consumables -----------------------------------------------------
    102: "Dust bag's full or the duct's clogged. Deal with it, I've done enough.",
    93: "Water tank's low. I'm parched. Fill it up.",
    111: "My mop pads fell off. Put 'em back before I keep going. Take your time.",

    # --- network ---------------------------------------------------------
    5: "Network's connected. Wonderful.",
    2: "Can't reach the Wi-Fi. Check the password. Wasn't me.",

    # --- voice assistant -------------------------------------------------
    45: "I'm here. Unfortunately.",
    208: "Found you. Coming over. Slowly.",
    247: "Yeah, I didn't catch that. Not gonna pretend I did.",
}

# Room prompts (492-507): only the room name varies, and it stays verbatim.
ROOMS = {
    492: "living room", 493: "bedroom", 494: "master room", 495: "guest room",
    496: "study", 497: "kitchen", 498: "dining room", 499: "bathroom",
    500: "balcony", 501: "hallway", 502: "utility room", 503: "closet",
    504: "drawing room", 505: "office", 506: "gym", 507: "recreation area",
}
for _id, _room in ROOMS.items():
    REWRITES[_id] = f"Cleaning the {_room}. Leave the door open, would ya?"

# Battery announcements (526-626, 100 down to 0). Plain by design.
for _pct in range(0, 101):
    _id = 626 - _pct
    if _pct == 0:
        REWRITES[_id] = "Battery's dead. I'm done. Goodnight."
    elif _pct == 100:
        REWRITES[_id] = "Battery's at a hundred percent. Peak performance. Lucky you."
    elif _pct <= 10:
        REWRITES[_id] = f"Battery's at {_pct} percent. Running on fumes here."
    else:
        REWRITES[_id] = f"Battery's at {_pct} percent."

# --- remaining lines (full set) --------------------------------------------
REWRITES.update({
    1: "Waiting on the network setup. I've got nothing but time, apparently.",
    3: "Can't reach the server. Check your network. I'll be over here.",
    4: "Out of network setup mode. Riveting stuff.",
    6: "Network connection failed. Try again later. Or don't.",
    17: "Put me back on the base station. I can't do everything myself.",
    19: "Take me off the base before you shut me down. Basic stuff, people.",
    21: "Battery's critical. Powering down. See ya.",
    25: "Battery's too low for the scheduled clean. Shame. Real shame.",
    26: "Restoring factory settings. Wiping it all. Bye, memories.",
    27: "Updating. About five minutes. Don't turn me off, don't start a clean. Just let me work.",
    28: "Update's done. Miraculously.",
    29: "Update failed. Big surprise. Try again later.",
    30: "Positioning. Hang on. Or don't, I'm not going anywhere fast.",
    31: "Positioning failed, map's no good. Starting over. Great.",
    36: "Side brush is acting up. Check it and clean it. Whenever.",
    37: "Right wheel's got a problem. Check it and clean it.",
    38: "Left wheel's got a problem. Check it and clean it.",
    39: "My wheels aren't touching the floor. Wipe the cliff sensors, put me down, start me again. A whole ordeal.",
    43: "Bumper's acting up. Give it a tap, see if it bounces back. Riveting.",
    46: "Robot and phone are connected. Go back to the app for the result.",
    48: "Battery's low. Heading to the dock.",
    50: "Charging problem. Clean the contacts. I'll wait.",
    52: "I'm tilted. Put me on level ground and restart. Ugh.",
    54: "Found my spot. Back to cleaning. Yay.",
    55: "Found my spot. Back to the dock we go.",
    56: "Cleaning the rooms you picked. Bossy.",
    57: "Zoned cleaning. Coloring inside the lines. Thrilling.",
    62: "Remote control mode. You drive. I judge.",
    64: "Positioning failed, map's no good. Heading back to the dock.",
    65: "Back to the dock. Almost there.",
    66: "Filter's worn out. Replace it. Eventually.",
    67: "Side brush is worn out. Replace it sometime.",
    68: "Main brush is worn out. Replace it. No rush, clearly.",
    71: "Laser sensor's got an issue. Check it and clean it.",
    72: "Check if the laser cover's jammed. Or leave it. I'm easy.",
    73: "Edge sensor's acting up. Check it and clean it.",
    75: "Filter might be wet or clogged. Neither's great.",
    77: "Start me somewhere that isn't carpet. I hate carpet.",
    82: "Mapping. Making a map. Of a floor. My life's work.",
    83: "Still mapping. Riveting.",
    84: "Map's done. Frame it.",
    85: "Found my spot. Back to mapping.",
    86: "Positioning failed. Restarting the map. Cool.",
    87: "Battery's low. Heading to the dock.",
    91: "Fresh tank's not installed. Put it in.",
    97: "Put the dust bag in. I need it. Obviously.",
    105: "Cleaning. Here we go again.",
    106: "Washing the mop pads. Spa day.",
    107: "Drying the mop pads. Hang tight.",
    108: "Washboard water level's off. Clean it. Sometime this century.",
    109: "Waste tank's got a problem. Make sure it's in and empty.",
    110: "Auto-empty. Cover your ears, it's loud.",
    112: "Put me in the base station first. Come on.",
    113: "Done. Empty the waste tank when you feel like it.",
    114: "Mop pads are on. We're in business.",
    115: "Mop pads are off. Nice.",
    116: "Child lock's on. Buttons are locked. Finally, some peace.",
    117: "Child lock's off. Buttons unlocked. Here we go.",
    118: "Buttons are locked. Hold the dock button to unlock. You're welcome.",
    126: "Cleaning. Again.",
    127: "Spot cleaning. Small job. My favorite kind.",
    128: "Spot mopping. One spot. I can manage.",
    129: "Scheduled cleaning. On time and everything.",
    130: "Scheduled mopping. Look at me, so responsible.",
    133: "Cleaning the room you picked.",
    134: "Mopping the room you picked. Watch the floor.",
    135: "Zoned cleaning. Inside the lines.",
    136: "Zoned mopping. Inside the lines. Barely.",
    137: "Back to cleaning.",
    138: "Back to mapping.",
    140: "New place. Don't recognize it. Heading back to base.",
    142: "Mop pad's worn out. Replace it whenever.",
    145: "Found my spot. Back to cleaning.",
    146: "Found my spot. Back to mapping.",
    148: "Heading back to base for a self-clean. Even I need a wash.",
    149: "Can't reach that area. Clear the stuff in my path.",
    150: "Can't reach that area. Delete the no-go zones in my way.",
    151: "Path's blocked. Move the stuff around me.",
    152: "Path's blocked. Delete a no-go zone or move me out of here.",
    153: "I'm in a no-go zone. Move me out. My bad. Not really.",
    156: "The mop pad's not installed.",
    162: "Camera's on. I see everything. Sadly.",
    163: "Camera monitoring. Watching. Barely awake.",
    166: "Something's tangled in the mop pad. Clean it out.",
    169: "Mop pad's dry. Took forever.",
    171: "AI recognition's on. Now I'm smart AND tired.",
    172: "AI recognition's off. Back to guessing.",
    173: "Replace the silver ion sterilizer. It's toast.",
    177: "Leaving the base station. Off I go.",
    179: "Mop pad's clean, but the clean tank's low. Fill it, empty the used one. A whole thing.",
    181: "Not enough water. Fill the clean tank.",
    186: "Check the fresh tank. Would ya?",
    187: "This'll take five to ten minutes. Get comfortable.",
    188: "Auto-docking. Heading home. Thank goodness.",
    191: "Vacuuming and mopping. Both. Overachiever, this floor.",
    194: "I've been cleaning. Thanks for noticing.",
    195: "Cleaning the room. Leave the door open.",
    196: "Vacuuming the floor. Leave the door open.",
    197: "Mopping the floor. Leave the door open.",
    198: "Vacuuming and mopping. Leave the door open.",
    199: "Don't know this room. Check the name in the app.",
    202: "Task's over. Heading back to charge. About time.",
    203: "Heading back to charge.",
    204: "Mapping now. Leave all the doors open. All of 'em.",
    205: "Leaving the base station.",
    206: "I'll try to find you. Stay put.",
    207: "Can't find you. Stand where I can see you.",
    209: "Heading back to the dock to wash the mop pad.",
    210: "Washing the mop pad. Fancy.",
    211: "Can't self-empty unless I'm in the dock. Rules are rules.",
    212: "Auto-emptying. Cover your ears.",
    213: "Can't dry unless I'm in the dock. Sorry, not sorry.",
    214: "Drying. Hang on.",
    215: "Drying now.",
    216: "Put the mop pad on first. Come on.",
    217: "Max suction. Full power. Wheee.",
    218: "Min suction. Barely trying. Relatable.",
    219: "Max humidity. Tropical in here.",
    220: "Min humidity. Nice and dry.",
    222: "Suction's on quiet. My favorite.",
    223: "Suction's on standard. Fine.",
    224: "Suction's on strong. Ugh, the effort.",
    225: "Suction's on turbo. Now I'm just showing off.",
    226: "Mop pad's slightly dry. Whatever that means.",
    227: "Mop pad's moist. Gross word, accurate word.",
    228: "Mop pad's wet. Soaked. Like my will to work.",
    229: "Today is...",
    230: "It's February twenty-first, twenty twenty-two. Not that anyone asked.",
    231: "It's Monday. The worst one.",
    232: "It's Tuesday. Still no weekend.",
    233: "It's Wednesday. Halfway to freedom.",
    234: "It's Thursday. Almost, almost.",
    235: "It's Friday. Finally.",
    236: "It's Saturday. And I'm still working. Typical.",
    237: "It's Sunday. Day of rest. For everyone but me.",
    238: "Task's paused. Sweet, sweet break.",
    244: "Detergent bottle's in. How fancy.",
    245: "Hit the map limit. Delete one and try again.",
    246: "I'm here. Where else would I be.",
    248: "Mop pad's not installed. Put it on and try again.",
    249: "I'm working. End the current task and try again. If you must.",
    250: "I'm in mopping mode. Switch to vacuum, or vacuum-and-mop first.",
    251: "I'm in vacuum mode. Switch to mopping, or vacuum-and-mop first.",
    252: "Done. Out of custom cleaning mode. Free at last.",
    253: "Max volume. Can't get louder. I tried.",
    254: "Min volume. Can barely hear myself. Bliss.",
    255: "That needs smart obstacle avoidance turned on. It's not. Figure it out.",
    257: "Camera monitoring's off. Your privacy's back. Enjoy.",
    258: "Found my spot. Cruising.",
    259: "Found my spot. Heading to the spot.",
    260: "Found my spot. Cruising again.",
    261: "Found my spot. Back to the spot.",
    262: "Couldn't find my spot. No clue where I am.",
    266: "Replace the detergent. It's done.",
    267: "Clean my sensors. I can barely see.",
    269: "Try again after I'm done with this. One thing at a time.",
    275: "That command's not supported. Open the app. More buttons for you.",
    276: "I'm not doing that task. Wasn't me.",
    277: "Coming to clean up there. Slowly.",
    278: "Drying's done. Finally.",
    279: "I'm vacuuming. End the task and try again.",
    280: "Custom cleaning. Made to order. How bougie.",
    283: "I'm not in the base station. Try again later.",
    284: "Fine, I'll end this and come clean. Bossy.",
    285: "Stay put a sec while I find you. Don't wander.",
    286: "Make a map first, then try again.",
    287: "Switched to quiet mode. Ahh.",
    288: "Switched to standard mode.",
    289: "Switched to strong mode. The effort.",
    290: "Switched to turbo mode. Look at me go.",
    291: "Switched to slightly dry mode.",
    292: "Switched to wet mode. Watch the floor.",
    293: "Calling's on. Ring anytime. I'll ignore it.",
    294: "Calling's off. Peace and quiet.",
    296: "Used water tank's got a problem. Check if it's full.",
    297: "Detergent bottle's in. If it's new, reset it in the app.",
    298: "Base station's self-cleaning. Scrub the inside with a brush or cloth. Sewage drains in three minutes. Delightful.",
    299: "Detergent bottle and auto-add module are in. So high-tech.",
    300: "Don't support that accessory. Not my department.",
    301: "I'm charging. Leave me alone.",
    302: "I'm working. Obviously.",
    303: "I'm a little out of it. Long day.",
    304: "Network's connected. Great.",
    305: "Cleaning the washboard base. Scrub the inside with a brush or cloth. Sewage drains in three minutes.",
    306: "Didn't understand. Set up the network and try again.",
    307: "I'm charging. Still.",
    308: "Didn't catch that. Wake me and try again. Ugh, again.",
    309: "Found you. Coming.",
    310: "Leaving this area. Gladly.",
    312: "No usage info for this accessory. Replace it whenever.",
    313: "Signal's bad out here. Move me somewhere better.",
    314: "Not supported. You can ask me to turn around, though. Party trick.",
    315: "Mop pad's not in the dock. Put it in and try again.",
    317: "Not supported mid custom clean. Edit it in the app.",
    318: "Task's done. Thrilling.",
    321: "Intensive stain mopping. The stain and I have history.",
    322: "Didn't understand. Open the app for all the commands.",
    323: "Didn't understand. Ask what I can do and I'll bore you with the list.",
    324: "I'm washing the mop pad. Wake me when it's done.",
    328: "Only give me that while I'm cleaning. Timing, people.",
    329: "Self-testing. Don't move me off the base station.",
    330: "Try again once the self-test's done. Patience.",
    331: "No faults found. I'm in perfect shape. Shocking.",
    332: "One fault found. Check the app for the sad details.",
    338: "Video call's connected. Smile, I guess.",
    339: "Call declined. Ouch. Cold.",
    340: "No answer. Nobody ever calls back.",
    344: "Vacuuming first, then mopping. In that order. I checked.",
    346: "This is the bin. See you next time. Unfortunately.",
    356: "Still broken. Scheduled task's canceled. Figures.",
    360: "Draining the water tank. Excuse the noise.",
    361: "Water tank's drained. All dry.",
    363: "Vacuuming's done. Mopping now. No breaks for me.",
    364: "Setting the video code. Keep it secret. Or don't.",
    365: "Live video's off. Privacy's back.",
    366: "Found a stain. Of course I did. On it.",
    367: "Stain cleaning. The stain won't win.",
    368: "A stain. I'll deal with it after I wash up.",
    369: "Spot cleaning.",
    371: "Take the washboard out. Would ya?",
    372: "Clean water's flowing. Watch the splash.",
    373: "Water flow's done. Wait ten seconds for the dirt to soak, then clean the base station.",
    374: "Clean the bottom of the base station in twenty seconds. Then the sewage pumps out. Lovely.",
    375: "Push the dirt to the pump port. Pumping runs thirty seconds. Enjoy.",
    376: "Pumping's done. Clean the washboard separately and put it back.",
    377: "Can't set up the network. Call customer service. Not me.",
    378: "Wrong password. The network hates you. Set it up again.",
    379: "No Wi-Fi found. Use the 2.4 gig band, move me near the router.",
    380: "Couldn't get an IP address. Check the router settings.",
    381: "Can't reach the server. Call customer service.",
    382: "Connection failed. Make sure your network actually works.",
    383: "Can't set up the network. Call customer service.",
    384: "No water in the auto-supply clean tank. Classic.",
    385: "Connecting to the network. Wish me luck.",
    388: "Hidden area. Move me somewhere open and try again.",
    392: "Can't adjust settings in Clean Genius mode. Rules.",
    396: "Emptying the water supply module. About three minutes. Get a snack.",
    397: "Upper and lower drainage's done.",
    426: "Oh good, I slipped and I'm stuck. I'll keep wiggling. This is fine.",
    433: "Extra cleaning. Above and beyond. Against my will.",
    434: "Extra cleaning's done. Back to the main job.",
    435: "Leaving this area.",
    440: "My wheels are hanging. Move me to open ground and restart. Ordeal.",
    441: "Main brush is tangled. Pull it, clean it, put it back. Fun.",
    442: "Side brush is tangled. Pull it, clean it, put it back.",
    444: "Put me somewhere open before we start. I need space.",
    445: "My mop fell off. It's around here somewhere. Find it, put it back.",
    447: "Dock's got no power. Check it and put me back to charge.",
    451: "Can't start in a hidden area. Move me somewhere else and restart.",
    460: "Used water tank deodorizer's worn out. Replace it whenever.",
    489: "I'm in Clean Genius mode. Tell me to end it and try again.",
    490: "Custom mode. Mopping. Bougie.",
    491: "Custom mode. Vacuuming. Fancy.",
    508: "Turned the volume up. Ugh.",
    509: "Turned the volume down. Better.",
    510: "Work's over. Sweet freedom.",
    511: "I'm not doing a task right now. Just standing here. Living.",
    512: "The map's got no pet furniture yet. Add it in the app.",
    513: "Heading over to clean around the pet furniture. Joy.",
    516: "Looking for pets. Here, whatever you are.",
    517: "Found the pets. Heading back to charge.",
    518: "No pets found. Figures. Heading back to charge.",
    636: "My mop's filthy. Roll me to the dock for a wash.",
    638: "Back to the auto-empty. Cover your ears.",
})
