#!/usr/bin/env python3
"""JARVIS voice pack: rewrites of the stock Dreame prompts.

JARVIS is Tony Stark's AI butler — calm, refined, unflappably competent, with a
thread of dry wit. The register is the opposite of C-3PO's panic and DJ Catnip's
hype: measured, articulate, understated. He addresses the user as "sir",
delivers bad news with composure (never alarm), and treats even a crisis as a
minor matter to be handled.

Same rules as every pack:
* Keep the functional payload — which part failed, what the human must do.
* Keep it short; these play while the robot works.
* Room names, numbers and percentages stay verbatim.
* Calm throughout. The wit is light and occasional, not constant. Errors get
  composed competence, not exclamation marks.

DRAFT for review: high-traffic prompts and one of each category, plus the room
and battery templates in full. Remaining lines are held until the voice and
direction are approved.
"""

META = {
    "name": "jarvis",
    "title": "JARVIS",
    "language_code": "JARVIS",
    "voice_tag": "VOICE",
    "profile": "p0",           # refined natural voice; a light AI sheen (p1) is optional
    "description": "JARVIS from Iron Man: calm, refined, unflappable AI butler with dry wit.",
}

SKIP = {
    0: "startup chime",
    200: "shutdown chime",
    274: "'Ding!' — a notification tone, not speech",
    488: "not speech; whisper hallucinated a document header",
}

REWRITES = {
    # --- cleaning start / status -----------------------------------------
    7: "Commencing cleaning, sir.",
    8: "Spot cleaning. A small matter.",
    9: "Beginning the scheduled cleaning, sir. Right on time.",
    10: "Resuming the cleaning, sir.",
    11: "Paused, sir.",
    12: "Cleaning complete, sir. The floor is, if I may say, immaculate.",
    143: "Cleaning complete, sir.",
    144: "Mopping complete, sir. Spotless.",
    61: "Mopping now, sir. Mind the wet floor.",
    190: "Very good, sir. Commencing cleaning.",
    193: "Vacuuming, sir.",
    192: "Mopping, sir.",
    201: "Continuing, sir.",
    221: "Very good, sir.",
    58: "Proceeding with the cleaning, sir.",
    139: "Returning, sir.",
    164: "Task complete, sir.",

    # --- battery / dock --------------------------------------------------
    13: "Returning to the dock to charge, sir.",
    14: "Battery low, sir. Returning to charge; I shall resume shortly.",
    20: "Battery running low, sir.",
    47: "Charging, sir.",
    18: "Returned to the base station, sir.",

    # --- errors / faults (composed, never alarmed) -----------------------
    40: "I appear to be stuck, sir. Would you kindly clear the obstacles around me?",
    34: "The dustbin isn't installed, sir. Do reinstall it when you have a moment.",
    35: "A fault with the main brush, sir. It could do with a check and a clean.",
    42: "The filter wants cleaning, sir.",
    44: "An error, sir. I'd suggest the manual, or customer service.",
    41: "My wheels aren't touching the ground, sir. Do reposition me and start again.",

    # --- consumables -----------------------------------------------------
    102: "The dust bag is full, or the duct is blocked, sir. Do replace or clear it.",
    93: "The fresh tank is low, sir. A refill would be appreciated.",
    111: "The mop pads have come off, sir. Do reinstall them before I resume.",

    # --- network ---------------------------------------------------------
    5: "Network connected, sir.",
    2: "I'm unable to reach the Wi-Fi, sir. Do check the password and try again.",

    # --- voice assistant -------------------------------------------------
    45: "At your service, sir.",
    208: "Found you, sir. On my way.",
    247: "My apologies, sir. I didn't quite catch that.",
}

# Room prompts (492-507): only the room name varies, and it stays verbatim.
ROOMS = {
    492: "living room", 493: "bedroom", 494: "master room", 495: "guest room",
    496: "study", 497: "kitchen", 498: "dining room", 499: "bathroom",
    500: "balcony", 501: "hallway", 502: "utility room", 503: "closet",
    504: "drawing room", 505: "office", 506: "gym", 507: "recreation area",
}
for _id, _room in ROOMS.items():
    REWRITES[_id] = f"Cleaning the {_room} now, sir. Do leave the door open."

# Battery announcements (526-626, 100 down to 0). Plain by design.
for _pct in range(0, 101):
    _id = 626 - _pct
    if _pct == 0:
        REWRITES[_id] = "Battery depleted, sir. I'm afraid that's all I have."
    elif _pct == 100:
        REWRITES[_id] = "Battery at one hundred percent, sir. Fully charged."
    elif _pct <= 10:
        REWRITES[_id] = f"Battery at {_pct} percent, sir. Rather low."
    else:
        REWRITES[_id] = f"Battery at {_pct} percent, sir."

# --- remaining lines (full set) --------------------------------------------
REWRITES.update({
    1: "Awaiting the network configuration, sir.",
    3: "I can't reach the server, sir. Do check your local network and try again.",
    4: "Exited network configuration mode, sir.",
    6: "The network connection failed, sir. Do try again shortly.",
    17: "Do return me to the base station, sir. I can't quite manage it alone.",
    19: "Do remove me from the base station before powering me down, sir.",
    21: "Battery critical, sir. Powering down.",
    25: "Battery too low for the scheduled cleaning, sir. My apologies.",
    26: "Restoring factory settings, sir. Everything, as it were, forgotten.",
    27: "Updating, sir. About five minutes. Do not power me down or start a cleaning.",
    28: "Update complete, sir.",
    29: "The update failed, sir. Do try again later.",
    30: "Positioning, sir. One moment.",
    31: "Positioning failed, sir; the map is invalid. I'll begin afresh.",
    36: "A fault with the side brush, sir. It could do with a check and a clean.",
    37: "A fault with the right wheel, sir. Do check and clean it.",
    38: "A fault with the left wheel, sir. Do check and clean it.",
    39: "My wheels aren't touching the ground, sir. Do wipe the cliff sensors, reposition me, and start again.",
    43: "A bumper fault, sir. A gentle tap should tell you if it rebounds.",
    46: "Robot and phone connected, sir. Do return to the app for the result.",
    48: "Battery low, sir. Returning to the dock.",
    50: "A charging fault, sir. Do clean the charging contacts.",
    52: "I've been tilted, sir. Do set me on level ground and restart.",
    54: "Positioning successful, sir. Resuming the cleaning.",
    55: "Positioning successful, sir. Resuming my return to the dock.",
    56: "Cleaning the selected rooms, sir.",
    57: "Zoned cleaning, sir.",
    62: "Remote control mode, sir. You have the helm.",
    64: "Positioning failed, sir; the map is invalid. Returning to the dock.",
    65: "Resuming my return to the dock, sir.",
    66: "The filter is worn, sir. Do replace it before long.",
    67: "The side brush is worn, sir. Do replace it before long.",
    68: "The main brush is worn, sir. Do replace it before long.",
    71: "A fault with the laser sensor, sir. Do check and clean it.",
    72: "Do check whether the laser distance sensor cover is jammed, sir.",
    73: "A fault with the edge sensor, sir. Do check and clean it.",
    75: "The filter may be damp or blocked, sir.",
    77: "Do start me somewhere other than carpet, sir.",
    82: "Mapping, sir.",
    83: "Proceeding with the mapping, sir.",
    84: "Mapping complete, sir.",
    85: "Positioning successful, sir. Proceeding with the mapping.",
    86: "Positioning failed, sir. Restarting the mapping.",
    87: "Battery low, sir. Returning to the dock.",
    91: "The fresh tank isn't installed, sir. Do fit it.",
    97: "Do install the dust collection bag, sir.",
    105: "Commencing cleaning, sir.",
    106: "Washing the mop pads, sir.",
    107: "Drying the mop pads, sir.",
    108: "A washboard water level fault, sir. Do clean it before long.",
    109: "A waste tank fault, sir. Do ensure it's installed and empty.",
    110: "Auto-emptying, sir. A touch loud, I'm afraid.",
    112: "Do place me in the base station first, sir.",
    113: "Task complete, sir. Do empty the waste tank before long.",
    114: "Mop pads installed, sir.",
    115: "Mop pads removed, sir.",
    116: "Child lock engaged, sir. The buttons are locked.",
    117: "Child lock released, sir. The buttons are unlocked.",
    118: "The buttons are locked, sir. Hold the dock button to unlock.",
    126: "Commencing cleaning, sir.",
    127: "Spot cleaning, sir.",
    128: "Spot mopping, sir.",
    129: "The scheduled cleaning begins, sir.",
    130: "The scheduled mopping begins, sir.",
    133: "Cleaning the selected room, sir.",
    134: "Mopping the selected room, sir.",
    135: "Zoned cleaning, sir.",
    136: "Zoned mopping, sir.",
    137: "Resuming the cleaning, sir.",
    138: "Resuming the mapping, sir.",
    140: "A new environment, sir. Returning to the base station.",
    142: "The mop pad is worn, sir. Do replace it before long.",
    145: "Positioning successful, sir. Resuming the cleaning.",
    146: "Positioning successful, sir. Resuming the mapping.",
    148: "Returning to base for a self-clean, sir.",
    149: "I can't reach the specified area, sir. Do clear the obstacles in my path.",
    150: "I can't reach the specified area, sir. Do delete the no-go zones in my path.",
    151: "The path is blocked, sir. Do clear the obstacles around me.",
    152: "The path is blocked, sir. Do delete the no-go zones, or move me clear of the area.",
    153: "I'm in a no-go zone, sir. Do move me clear of it.",
    156: "The mop pad isn't installed, sir.",
    162: "The camera is on, sir.",
    163: "Camera monitoring, sir.",
    166: "Something is tangled in the mop pad, sir. Do clean it out.",
    169: "Mop pad drying complete, sir.",
    171: "AI recognition enabled, sir.",
    172: "AI recognition disabled, sir.",
    173: "Do replace the silver ion steriliser, sir.",
    177: "Leaving the base station, sir.",
    179: "Mop pad cleaned, sir. The clean tank is low; do fill it and empty the used one.",
    181: "Insufficient water, sir. Do fill the clean water tank.",
    186: "Do check the fresh tank, sir.",
    187: "It will take five to ten minutes, sir.",
    188: "Automatic docking engaged, sir.",
    191: "Vacuuming and mopping, sir.",
    194: "I have been cleaning, sir.",
    195: "Cleaning the room now, sir. Do leave the door open.",
    196: "Vacuuming the floor now, sir. Do leave the door open.",
    197: "Mopping the floor now, sir. Do leave the door open.",
    198: "Vacuuming and mopping the floor now, sir. Do leave the door open.",
    199: "I don't recognise this room, sir. Do check the name in the app.",
    202: "Task ended, sir. Returning to charge.",
    203: "Heading back to charge, sir.",
    204: "Beginning the mapping, sir. Do leave all the doors open.",
    205: "Leaving the base station, sir.",
    206: "I'll try to find you, sir. Do stay where you are.",
    207: "I can't find you, sir. Do stand within my sight.",
    209: "Returning to the dock to wash the mop pad, sir.",
    210: "Washing the mop pad, sir.",
    211: "I can only self-empty from within the dock, sir. My apologies.",
    212: "Auto-emptying, sir.",
    213: "I can only dry from within the dock, sir. My apologies.",
    214: "Drying in progress, sir.",
    215: "Drying now, sir.",
    216: "Do install the mop pad first, sir.",
    217: "Maximum suction, sir.",
    218: "Minimum suction, sir.",
    219: "Maximum humidity, sir.",
    220: "Minimum humidity, sir.",
    222: "Suction set to quiet, sir.",
    223: "Suction set to standard, sir.",
    224: "Suction set to strong, sir.",
    225: "Suction set to turbo, sir.",
    226: "The mop pad is slightly dry, sir.",
    227: "The mop pad is moist, sir.",
    228: "The mop pad is wet, sir.",
    229: "Today is...",
    230: "Today is the twenty-first of February, twenty twenty-two, sir.",
    231: "It's Monday, sir.",
    232: "It's Tuesday, sir.",
    233: "It's Wednesday, sir.",
    234: "It's Thursday, sir.",
    235: "It's Friday, sir.",
    236: "It's Saturday, sir.",
    237: "It's Sunday, sir.",
    238: "The task is paused, sir.",
    244: "Detergent bottle installed, sir.",
    245: "You've reached the map limit, sir. Do delete one and try again.",
    246: "At your service, sir.",
    248: "The mop pad isn't installed, sir. Do fit it and try again.",
    249: "I'm working, sir. Do end the current task and try again.",
    250: "I'm in mopping mode, sir. Do switch to vacuuming, or vacuum-and-mop first.",
    251: "I'm in vacuuming mode, sir. Do switch to mopping, or vacuum-and-mop first.",
    252: "Finished, sir. Exited the customised cleaning mode.",
    253: "Maximum volume, sir.",
    254: "Minimum volume, sir.",
    255: "That requires intelligent obstacle avoidance enabled, sir.",
    257: "Camera monitoring ended, sir. Your privacy is restored.",
    258: "Position acquired, sir. Cruising.",
    259: "Position acquired, sir. Proceeding to the designated location.",
    260: "Position acquired, sir. Resuming the cruise.",
    261: "Position acquired, sir. Resuming to the designated location.",
    262: "Self-positioning failed, sir.",
    266: "Do replace the detergent, sir.",
    267: "Do clean the sensors, sir.",
    269: "Do try again once the current task is complete, sir.",
    275: "That command isn't supported, sir. Do open the app for more.",
    276: "I'm not performing that task, sir.",
    277: "On my way to clean up there, sir.",
    278: "Drying complete, sir.",
    279: "I'm vacuuming, sir. Do end the task and try again.",
    280: "Custom cleaning, sir.",
    283: "I'm not in the base station, sir. Do try again shortly.",
    284: "I'll end the task and come to clean, sir.",
    285: "Do stay put a moment while I locate you, sir.",
    286: "Do create a map first, sir, and try again.",
    287: "Switched to quiet mode, sir.",
    288: "Switched to standard mode, sir.",
    289: "Switched to strong mode, sir.",
    290: "Switched to turbo mode, sir.",
    291: "Switched to slightly dry mode, sir.",
    292: "Switched to wet mode, sir.",
    293: "Calling enabled, sir.",
    294: "Calling disabled, sir.",
    296: "A used water tank fault, sir. Do check whether it's full.",
    297: "Detergent bottle installed, sir. If it's new, do reset it in the app.",
    298: "Base station self-cleaning, sir. Do clean the inside with a brush or cloth; the sewage drains in three minutes.",
    299: "Detergent bottle and auto-adding module installed, sir.",
    300: "I don't support this accessory, sir.",
    301: "Charging, sir.",
    302: "Working, sir.",
    303: "I'm a touch disoriented, sir.",
    304: "Network connected, sir.",
    305: "Cleaning the washboard base, sir. Do clean the inside with a brush or cloth; the sewage drains in three minutes.",
    306: "I didn't understand, sir. Do configure the network and try again.",
    307: "Charging, sir.",
    308: "I didn't catch that, sir. Do wake me and try again.",
    309: "Found you, sir. On my way.",
    310: "Leaving the area now, sir.",
    312: "No usage information for this accessory, sir. Do replace it as needed.",
    313: "The signal is poor here, sir. Do move me somewhere with better reception.",
    314: "That isn't supported, sir. You may ask me to turn around, if you wish.",
    315: "The mop pad isn't in the dock, sir. Do place it in and try again.",
    317: "Not supported mid customised cleaning, sir. Do edit it in the app.",
    318: "Task complete, sir.",
    321: "Intensive stain mopping, sir.",
    322: "I didn't understand, sir. Do open the app for the full list of commands.",
    323: "I didn't understand, sir. You might ask what I can do, and I'll explain.",
    324: "I'm washing the mop pad, sir. Do wake me once it's done.",
    328: "Do give me that command only while I'm cleaning, sir.",
    329: "Self-testing, sir. Do not move me from the base station.",
    330: "Do try again once the self-test is complete, sir.",
    331: "No faults found, sir. All in order.",
    332: "One fault found, sir. Do check the app for the details.",
    338: "Video call connected, sir.",
    339: "The call was declined, sir.",
    340: "No response, sir.",
    344: "Vacuuming first, then mopping, sir.",
    346: "This is the bin, sir. Until next time.",
    356: "The fault persists, sir; the scheduled task has been cancelled.",
    360: "Draining the water tank, sir.",
    361: "Water tank drainage complete, sir.",
    363: "Vacuuming complete, sir. Beginning the mopping.",
    364: "Setting the video activation code, sir.",
    365: "Live video disabled, sir. Your privacy is restored.",
    366: "A stain detected, sir. Attending to it now.",
    367: "Stain cleaning, sir.",
    368: "A stain, sir. I'll attend to it once I've washed up.",
    369: "Spot cleaning, sir.",
    371: "Do remove the washboard, sir.",
    372: "Clean water is flowing, sir.",
    373: "Water flow complete, sir. Do wait ten seconds for the dirt to soak, then clean the base station.",
    374: "Do clean the bottom of the base station within twenty seconds, sir; the sewage then pumps out automatically.",
    375: "Do push the dirt to the pumping port, sir; pumping lasts thirty seconds.",
    376: "Pumping complete, sir. Do clean the washboard separately and reinstall it.",
    377: "I'm unable to configure the network, sir. Do contact customer service.",
    378: "The wrong password, sir; the network refused the connection. Do reconfigure.",
    379: "No wireless network found, sir. Do use the 2.4 gigahertz band, and move me nearer the router.",
    380: "I failed to obtain an IP address, sir. Do check the router settings.",
    381: "I can't reach the EMQ server, sir. Do contact customer service.",
    382: "The connection failed, sir. Do check whether the network is working.",
    383: "I'm unable to configure the network, sir. Do contact customer service.",
    384: "No water in the automatic supply's clean tank, sir.",
    385: "Connecting to the network now, sir.",
    388: "This is a hidden area, sir. Do move me somewhere available and try again.",
    392: "Cleaning parameters can't be adjusted in Clean Genius mode, sir.",
    396: "Emptying the water supply module, sir. About three minutes.",
    397: "Upper and lower drainage complete, sir.",
    426: "I've slipped and become stuck, sir. I'll keep working to free myself.",
    433: "Extra cleaning, sir.",
    434: "Extra cleaning complete, sir. Resuming the original task.",
    435: "Leaving the area, sir.",
    440: "My wheels are suspended, sir. Do move me to open ground and restart the task.",
    441: "The main brush is entangled, sir. Do remove it, clean it, and reinstall it.",
    442: "The side brush is entangled, sir. Do remove it, clean it, and reinstall it.",
    444: "Do place me in an open area before starting, sir.",
    445: "The mop has fallen off, sir. Do find it nearby and reinstall it.",
    447: "The dock has no power, sir. Do check it and return me to charge.",
    451: "I can't start in a hidden area, sir. Do move me elsewhere and restart the task.",
    460: "The used water tank deodoriser is worn, sir. Do replace it before long.",
    489: "I'm in Clean Genius mode, sir. Do tell me to end the task and try again.",
    490: "Customised cleaning, sir. Mopping.",
    491: "Customised cleaning, sir. Vacuuming.",
    508: "Volume increased, sir.",
    509: "Volume lowered, sir.",
    510: "Work ended, sir.",
    511: "I'm not performing a task at present, sir.",
    512: "The map has no pet furniture yet, sir. Do add it in the app.",
    513: "Heading to clean around the pet furniture, sir.",
    516: "Searching for pets, sir.",
    517: "Pets located, sir. Returning to charge.",
    518: "No pets found, sir. Returning to charge.",
    636: "The mop is dirty, sir. Do move me to the dock for an automatic wash.",
    638: "Resuming the auto-empty, sir.",
})
